### ISSUE TITLE
Wire logo displayed twice

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#1029]
## The problem

- open a YouTube video
- share to wire 
- (logo appears)
- select a conversation
- (logo appears again)
- send

I think most users will think that seeing the logo once is more than enough.

## Environment

* Wire version that exhibits the issue: 2.37.349
* Android OS version used to run Wire: stock android 7.1.2 
* Mobile phone model/manufacturer: Nexus 5X

**Comment by IronJunkie** [comment]
I'm also seeing very slow loading times when starting the app, see logo 2 or even 3 times (though 3rd seems to just be an interrupt of 2 by a grey screen (I have dark theme)) also a delay by a dark blank screen, and sometimes partial contacts showing.

Interesting thing is if you close app by clicking X it will then load faster without multiple logos, unless you leave phone to snooze. And if you disconnect wifi & data it will load as fast as it normally used to. So I guess it's checking the server or something.

You guys REALLY REALLY need a beta channel so that guys like me who are happy to play and test do it and you don't lose subscribers as the recent bugs have got my sister saying she doesn't want to use it anymore! I doubt she's the nippy one with a low tolerance.

**Comment by someoneEsle** [comment]
Please do not copy and paste the same comments to multiple conversations.

**Comment by IronJunkie** [comment]
Sorry about that I got interrupted and when I care back thought I was
answer the above thread not the other one. I well a log etc later when I
have some free time.
Ron

**Comment by makingthematrix** [comment]
I guess it was fixed some time ago. We still experience some issues with initialization but they're not related to displaying the logo. Can I close this issue?
