### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by JexPY** [wireapp/wire-android#1080]
## The problem

Hello wire group, I have  2 problems  with wire app yet. 
1. That's UI optimization, it has frame drops while opening new tabs (settings or chat ones)
2. Notifications, I am not getting them nor on lock nor while the app is opened. (and yes I have granted permissions) 

## Environment

* Wire version that exhibits the issue: The latest version from Play Store
* Android OS version used to run Wire: Android 7.0
* Is this a custom firmware or a stock one: It's stock but with Emui 5.0
* Mobile phone model/manufacturer: Huawei p8 lite (2017) Ram: 3gb 
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Tested only on wifi

## Details

App loads pretty fast but frames are dropping while trying to start new chat or open tab.

Am ready to help, cause really liked the idea of truly encrypted chat, so feel free to ask me for any kind of help. I can even install any beta or pre-beta versions or developer versions so use me am here to help.

Best Regards.

**Comment by someoneEsle** [comment]
Hi, thank you for reporting this. Please avoid vague sentences such as "latest version from the play store" -- we need the exact app version which you can find in Settings>About>Version. We need it because sometimes it takes a while for an update to reach your play store, and also three weeks from now there will be a new "latest version" anyway :) So which version are you on?

We are currently working on improving the performance of the app, especially when loading for the first time. It would help us to get a log from your phone, captured right after you see the visual glitches you described. You can take it from Settings>Advanced>Submit debug report.

As for the notifications, see here: https://github.com/wireapp/wire-android/issues/253
We usually try to keep issues separated though, so if you have any problem with notifications please write in one of our other threads.
Thanks!

**Comment by JexPY** [comment]
Thank you for quick response!
The Wire version : 2.39.356
package: com.wire
app version: 356
zms version: 106.2.390
device: HUAWEI PRA-LA1 | PRA-LA1 | HUAWEI | HUAWEIPRA-LA1
version: 7.0 | REL

Sorry no log cause : 
###### LogCat:
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by marcoconti83** [comment]
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.
