### ISSUE TITLE
Wire doesn't autostart on phone boot.

### ISSUE THREAD

**Issue by mastad0n** [wireapp/wire-android#1119]
## The problem

Wire doesn't start by itself when my phone boots up. 

## Environment

* Wire version that exhibits the issue: 2.40.357
* Last Wire version that did not exhibit the issue (if applicable): n/a
* Android OS version used to run Wire: 6.0
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: BLU R1 HD
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Happens on any network

## Details

Phone starts, I tap on Wire and the startup screen appears, indicating that it was in off state.

I also don't get notifications until I start it.

**Comment by someoneEsle** [comment]
Hi, I think I need to clarify some things. :)
First of all, when you launch Wire and you see the logo it does not necessarily means that Wire was not active in the background.
However, because you only receive notifications after you launch the app yourself, it does look like Wire was not active in the background. Some phones prevent some apps from autostarting, and I'm guessing this is what is happening on yours. Could you please go into the settings and check if you can whitelist Wire so that it can autostart? You may find such setting in the battery settings, or in a dedicated section.
Let me know if that helps.

**Comment by mastad0n** [comment]
> when you launch Wire and you see the logo it does not necessarily means that Wire was not active in the background.


You taught something new today :) I always thought this was the case with other apps too. Thank you!!

I will whitelist Wire and let it run for a few days and report back!

Thanks again @someoneEsle

**Comment by someoneEsle** [comment]
Hey, have you noticed any improvements?

**Comment by mastad0n** [comment]
@someoneEsle sorry for the late reply, it's fixed thanks to your suggestion of white-listing it!
