### ISSUE TITLE
Check for messages on network change

### ISSUE THREAD

**Issue by amenk** [wireapp/wire-android#1204]
## The problem

In some countries, Internet is expensive and as well are push notifications unreliable.
When offline and going online from time to time, message popups do not show.

## Environment

* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Going online infrequently

## Details

1. Go offline
2. Communication Partner sends a message
3. Go online
4. Message not indicated 

## Suggestion

Check for messages whenever the device goes online. (network change)

**Comment by someoneEsle** [comment]
Hi, thanks for reporting. This is a known bug we are working on

**Comment by amenk** [comment]
what is the other bug ticket? so this can be closed? any estimate?

**Comment by someoneEsle** [comment]
See #1101 
It's rather high on our priority list right now. I cannot say when it will be fixed, but we are working on a fix.

**Comment by amenk** [comment]
I am not talking about loosing messages, just that there is no notification popup. I think if you open wire, it syncs..

**Comment by makingthematrix** [comment]
There were a lot of changes to that functionality since 2017, but I guess this recent fix might be connected to the problem: https://github.com/wireapp/wire-android/pull/2616 . It's going to be included in the next release, and I guess then I'll be able to close this ticket if there will be no additional comments.
