### ISSUE TITLE
Canceling a video file upload deletes the file from the file-system too

### ISSUE THREAD

**Issue by Gregory-K** [wireapp/wire-android#1243]
## The problem
Interrupting/Canceling a video file upload deletes the file from the file-system too.
The video file has to be shared to Wire from a third party application.

## Environment

* Wire version that exhibits the issue: 3.1.369
* Last Wire version that did not exhibit the issue (if applicable): -
* Android OS version used to run Wire: 6.0.1
* Is this a custom firmware or a stock one: stock ROM rooted
* Mobile phone model/manufacturer: Sony Z3 Compact
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi

## Details

Select a video file in a "file explorer" or a "media album" application.
Choose to share it with Wire. Choose recipient.
Cancel the upload process.
Video file gets deleted from the file system (internal or sd-card).
(the first time it happened I tried a PhotoRec recovery without success!)

Other file-types remain intact after upload canceling. It may has something to do with the video transcoding procedure?

## Link to Debug logs

If asked I can send a log.

**Comment by tokariu** [comment]
I had the same issue and THIS is really F*CKED UP. I lost a valuable unique video clip file due to this bug, because wire also deleted the video file from my phones sdcard. it should have deleted it only from the conversation not the phone memory!

What happened?
-> I shared a video clip file by selecting the file in the file-explorer -> share  option.
-> selected my wire contact file. 
-> wire tried to send, but it failed and gave me an error msg.
-> did not try to resend, but tried to delete the failed message.
-> selected "delete for all" not "just for me".
-> the message was deleted.
-> when i tried to locate the video file on my phone memory to resend it, i realized that wire had deleted the video clip file from my phones memory without any warning!
-> lost the file forever.

This must not happen!

**Comment by Gregory-K** [comment]
Finally! I am not on my own ... :)

Bug replicated also on a Lenovo Tablet running Android 4.4.4 (rooted).
Not replicated on a Xiaomi Redmi 4 running Android 6 (rooted) though.

I will check more devices whenever I can.

**Comment by someoneEsle** [comment]
Hey everyone, I have tested this a few days ago but was not able to reproduce. I'll try on more devices today, but could you please send the log? It's very important to us that you provide complete information, otherwise we will end up prioritizing issues where we already have all the information we need to start working.
Also, please try to keep the conversation friendly and curse-free. We are here to help :)

**Comment by someoneEsle** [comment]
I was able to reproduce, no need for the logs anymore. Thanks for reporting!

**Comment by makingthematrix** [comment]
The functionality was rewritten and I can't reproduce the bug. I'll close the ticket - please reopen if it happens again.
