### ISSUE TITLE
Disable link preview for received messages: Privacy concern

### ISSUE THREAD

**Issue by RITFW** [wireapp/wire-android#1302]
I have disabled message preview for links. Unfortunately this does not disable the preview from messages I get. And this is a privacy as well as a security concern, as my device connects to the websites I get links from. As I would like to decide if and where I open the links I would highly appreciate the possibility to disable previews for the messages I get. I prefer using the Tor Bowser Bundle in a sandbox and not having a messenger connect to anything beside the necessary servers.

* Wire version: 3.3.374 (Android); 3.0.2816 (Linux AppImage 32bit)
* Android: 7.1.2 (LineageOS; without Google services)
* Mobile phone model/manufacturer: KLTE

**Comment by someoneEsle** [comment]
Hi, the link preview is generated on the sender's side. When you receive a link preview, it's because the other person has sent both the link and the image in its preview -- so your client doesn't have to connect to the website to fetch any data.
I will close this issue as the current design already takes into account privacy/security concerns, but if you have further questions don't hesitate to get back!

**Comment by RITFW** [comment]
Hi someoneEsle,

thank you so much for the clarification. And sorry that I misinterpreted the FAQs. 

Keep on doing such a great job!
