### ISSUE TITLE
Cannot disable debug logging(?)

### ISSUE THREAD

**Issue by ganego** [wireapp/wire-android#1355]
## The problem

Cannot disable debug logging.

## Environment

* Wire version that exhibits the issue: 3.4.382
* Last Wire version that did not exhibit the issue (if applicable): -
* Android OS version used to run Wire: 7.0
* Is this a custom firmware or a stock one: Xiaomi.eu ROM, MIUI9
* Mobile phone model/manufacturer: Xiaomi Redmi Note 4X (Snapdragon)
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wifi

## Details

While wanting to report something else I realized that I cannot enable or disable debug logging.
According to the section below "How to send detailed debug report from Wire" you have to tap "Wire swiss GmbH" 10 times to toggle it. But I never get any notification telling me if it's actually enabled or disabled - it seems to be enabled though, as I can save the report and it has recent dates in it.
I actually wanted to report high CPU usage while Wire runs in background compared to WA, probably it's because of the log running.

## Link to Debug logs

Create a [GIST](https://gist.github.com) which is a paste of your Wire logs, and link them here.
It is recommended to directly contact our [customer support](mailto:support@wire.com) and send the debug report by email, because it can potentially contain some private information, that you don't want to share to the public.

## How to send detailed debug report from Wire:

1. Go to Settings -> About
2. Tap "Wire swiss GmbH" 10 times
3. Reproduce your issue
4. Send the report from Settings -> Advanced -> Submit debug report
5. Go to Settings -> About
6. Tap "Wire swiss GmbH" 10 times again to disable detailed debug reports, because this slows down Wire

**Comment by someoneEsle** [comment]
Hey, thanks for flagging. We should probably update the list of steps because it is outdated :) The reason why we were asking users to tap 10 times on "Wire swiss" is because that way you would turn on more verbose logging. However, that is not the case anymore.
The reason why Wire has high CPU usage is very unlikely to be related to the log -- it is probably a combination of your device/network condition, as your reports looks similar to others we have received (https://github.com/wireapp/wire-android/issues/853).
