### ISSUE TITLE
Wire doesn't receive messages unless it is open on the screen

### ISSUE THREAD

**Issue by whateva** [wireapp/wire-android#1407]
## The problem

Wire won't receive messages unless it is open on the screen
**Also applies to pings, and calls

## Environment

* Wire version that exhibits the issue: 3.6.3911
* Last Wire version that did not exhibit the issue (if applicable): n/a
* Android OS version used to run Wire: 8.1.0
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Google Pixel 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE & Wi-Fi, occurs on all network types

This has been occuring across multiple different carriers, devices, and android versions both stock and custom for a long time. I just decided to report it now.
## Details

1 Tell somebody to send you a message in ten seconds
2 Take wire off your screen either by
 A) locking your device
 B) teasing home button to go to home screen
 C) use multitasking menu to actually close wire
3 You won't receive your message until you reopen wire

**Comment by someoneEsle** [comment]
Hi, can you capture logs and send them when this happens? Thanks.

**Comment by Transisto** [comment]
Same issue, Wire notification come in bust almost an hour later.

**Comment by Strit** [comment]
Also happens to me.

Android: 8.0 Orea
OS: OxygenOS
Phone: OnePlus 3
Wire version: 3.6.391 (from Google Play Store)

**Comment by someoneEsle** [comment]
Could you guys try this? https://support.wire.com/hc/en-us/articles/203624294-What-can-I-do-if-I-m-not-getting-any-notifications-on-Android-
The options may be in different menus depending on your phone model, but you should get an idea of what to look for in your settings

**Comment by RITFW** [comment]
I have notification problems as well.

Wire version: 3.6.391 (website release)
Android: LineageOS 14.1-20180215-NIGHTLY-klte (based on Android 7.1.2); no GCM, GSF
Mobile network: WIFI & mobile (mostly LTE)

The notification is really unreliable, when the APP is closed for some time the notifications stop working and sometimes I even have to kill the APP and open it again to get the latest messages from the server (I already received them on the Desktop application, so sending worked out fine). 

I have the same system settings for Wire, Telegram, Threema and Conversations and beside Wire all notifications work fine, even when the APPs weren't opened recently. Friends told me that they have the same problem on iOS as well. I've gone as well through the steps someoneEsle posted recently.

I really like Wire, but this lets me start thinking migrating more contacts to Conversation as the data privacy is better due to decentralization and notifications work fine there. Is there any chance that the notification issue will be fixed with the next version of WIre? I really like the APP and would like to continue using the otherwise well done APP ;)

**Comment by Strit** [comment]
"Could you guys try this? https://support.wire.com/hc/en-us/articles/203624294-What-can-I-do-if-I-m-not-getting-any-notifications-on-Android-
The options may be in different menus depending on your phone model, but you should get an idea of what to look for in your settings"

This seems to have "fixed" my issue. At least it's a workaround. The question is, why did it stop doing it in the first place.

**Comment by RITFW** [comment]
I already followed the instructions on the Wire support website and they didn't help with the notifications. And I don't think that my phone restricts too much as all other messaging APPs receive notifications just fine. Once I leave wire unattended for about 30 minutes the notifications stop working.

**Comment by pkrakowiak** [comment]
Resetting notifications from within the app doesn't help. Other app's notifications work fine (for example WhatsApp).

I'm on Oreo, too. Latest Wire version from Google Play. Newest OxygenOS, official image.

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by marcoconti83** [comment]
Hi all,
in case it was missed, there's a checklist to go through if you notifications are still acting up: https://support.wire.com/hc/en-us/articles/203624294-What-can-I-do-if-I-m-not-getting-any-notifications-on-Android-

**Comment by marcoconti83** [comment]
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.
