### ISSUE TITLE
Ability to attach multiple images/videos

### ISSUE THREAD

**Issue by aqeeliz** [wireapp/wire-android#152]
This is a feature request: Please add an ability to share multiple images (and videos) at a time. Currently you have to share one picture at a time, which can be very slow if you're sharing more than a couple images.

**Comment by bjoernherbig** [comment]
we have that feature on our roadmap. no timeline yet on it though.

**Comment by orangesunny** [comment]
I am asking for this too! And also a gallery/image picker that would show the latest pictures in the phone would be useful. Like in every other messaging app I know on Android.

Thank you!

**Comment by makingthematrix** [comment]
> I am asking for this too! And also a gallery/image picker that would show the latest pictures in the phone would be useful. Like in every other messaging app I know on Android.
> 
> Thank you!

Hi,
Due to the way we handle messages appearing in a conversation, it would be very difficult for us to move from "one message - one asset" to "one message - multiple assets" approach. We dropped the idea. Sorry.

As for the image picker: Do you mean something else than the gallery you see when you tap on the photo icon? If that gallery is not enough, after opening it, you can see a circular icon in the bottom-right corner which takes you to the standard Android gallery.
