### ISSUE TITLE
Poor battery performance when using WebSocket

### ISSUE THREAD

**Issue by xSmurf** [wireapp/wire-android#164]
The battery performance with WebSocket is abysmal. Turns my 2~3days of standby time to roughly 10h. I expect some hit, obviously, but this is pretty extreme. Maybe it would be possible to allow tweaking the polling time to reduce battery?

**Comment by someoneEsle** [comment]
What device are you using and what version of Android?

**Comment by xSmurf** [comment]
Nexus 5X on Nougat

**Comment by Be-ing** [comment]
i haven't tested it myself, but I have read that [Conversations](https://github.com/siacs/Conversations) managed to implement push notifications on Android in a battery efficient way without GCM. You may want to look at how [Zom](https://github.com/zom/Zom-Android) is doing it too.

I appreciate that the Wire team understands the importance of running Wire without GApps.

**Comment by h-2** [comment]
I have been using wire for a while now without GAPPS and on the first day the battery drain was really high, but then somehow it got completely normal. I still have LibreSignal running which also maintains a websocket connection and according to android it drains more battery than Wire.

**Comment by sschueller** [comment]
Battery consumption seems excessive when compare to other apps.
![screenshot_20161223-084855](https://cloud.githubusercontent.com/assets/1180107/21449832/727a3fea-c8f1-11e6-8144-0e093d151c17.png)

**Comment by h-2** [comment]
> I have been using wire for a while now without GAPPS and on the first day the battery drain was really high, but then somehow it got completely normal. I still have LibreSignal running which also maintains a websocket connection and according to android it drains more battery than Wire.

After some more time using WireApp, I have to say that power usage varies strongly between "not significant" to "more than everything else combined". I have yet to see a pattern, not moving at all seems to always result in low battery usage, but moving for a lot of movement it can be both low and high.
I have also experienced rare loss of updates where apparently something went wrong with the websockets.

**Comment by h-2** [comment]
Here an example of where wire really, drained the battery:
![screenshot_20170115-154313](https://cloud.githubusercontent.com/assets/2996863/22024835/a23adf1c-dccb-11e6-849c-f288bc4c0ce6.png)

Note that it "only" says 10%, however on-rime was reduced from over 24h to roughly 6-7h. After I killed the wire app, everything went back to normal.

**Comment by Be-ing** [comment]
> After some more time using WireApp, I have to say that power usage varies strongly between "not significant" to "more than everything else combined". I have yet to see a pattern, not moving at all seems to always result in low battery usage, but moving for a lot of movement it can be both low and high.

I have noticed this too. Occasionally, Wire is a big battery drain, but most of the time it is not. I have not noticed a pattern either.

**Comment by jdiercks** [comment]
+1

I'm also seeing unexpected battery usage from Wire on Android.

**Comment by h-2** [comment]
Signal now has websocket support officially and it also has a background deamon to re-establish connection in case something with the web-sockets goes wrong (telco times out connection earlier than they should).
It works really well and has no negative impact on my battery at all. Can you maybe have a look at how they do it?

**Comment by someoneEsle** [comment]
Actually they do have problems too (https://github.com/WhisperSystems/Signal-Android/issues/1298). Since it very much depends on the phone, I don't know if looking at their implementation will help (though it could). You may just be lucky to have it work well for you, while other people may find Wire to have a lower impact on their battery. I guess it depends. ^^

**Comment by h-2** [comment]
@someoneEsle that's before 3.30.0, they have changed stuff for the most recent release.

**Comment by iddno** [comment]
I'm using latest WIRE version on Android, with a HTC 10 and Android 7.1.2 without gapps or any Google services tho! The Battery drain is massive and not normal or acceptable at all. I will deinstall this app until this is fixed. This app drains almost my entire battery life over one day, just alone, it is ridiculous. 

https://mega.nz/#!oLg0hC5D!wdQytkgKCo1e2rUKV_XfPoz0YKAfOaB3FEmdn5Zj3uY

I love WIRE and how the devs do work on it and keep it running and improving. But this has to be handled with priority imho.

**Comment by itworksjbo** [comment]
Turns out this appears to be a bug only affecting the never versions. Had an old version (2.28.317) running without any battery issues, Updated to the newest version (2.33.336) after talking to someone who was complaining about high power drainage. Both of us run google-free androids.

Pictures: Before and after update.

![3b12433f69bc507d](https://cloud.githubusercontent.com/assets/12223583/26769654/e857d3e0-49b0-11e7-9767-370fed790da9.png)
![d03bd88907c71fb0](https://cloud.githubusercontent.com/assets/12223583/26769655/e859cc40-49b0-11e7-8301-9ecca5ae0026.png)

**Comment by Larx** [comment]
Any experiences with MicroG? I use this free GApps replacement, and Wire registers with it and receives messages with it (according to MicroG settings).

However, Wire is constantly running in the background (at least at 1% cpu usage in task monitors, even if nothing is happening, and all other apps are at 0). Consequently, Wire is always relatively high in my battery stats (with a very casual usage of a zero to a few messages a day, it contends with Firefox in terms of battery usage, which somhow does not fit together).

So, does Wire somehow not recognize that it can use MicroG and does alternative polling instead!?

**Comment by Awerick** [comment]
I know this issue is about battery performance if **WebSocket** is used – in contrast to the default case of using **GCM** which should be the case if [Google Play Services](https://play.google.com/store/apps/details?id=com.google.android.gms) or [microG](https://microg.org/) is installed. But there are now some comments that the issue started with one of the recent Wire updates and that it was fine before – which is also the case for me.
Is it correct that all of us having the problem only recently have actually _Google Play Services_ or _microG_ installed? In this case we should maybe discuss this in issue #853 that is not specifically about WebSocket.

_However I could resolve the problem for microG and for another device with preinstalled Google Play Services (but without a Google account, so no automatic updates) by manually updating them!_
For more details on this see my [comment in #853](https://github.com/wireapp/wire-android/issues/853#issuecomment-310673212).

My speculation about the problem with the recent update is: The new Wire update relies on a newer GCM version and if this is not found, Wire does not raise a warning but _silently_ falls back to WebSocket. Thus the GCM users now experience the same battery drain as the WebSocket users; so issue #853 would still be related to this WebSocket issue.

**Comment by joaobarcia** [comment]
Might it be related to #853 ?

**Comment by Jasper-Ben** [comment]
@Awerick No, I'm using a google-free phone. So this effects WebSocket and GCM likewise since recent versions.

**Comment by someoneEsle** [comment]
Please read my comment here: https://github.com/wireapp/wire-android/issues/853#issuecomment-320602500. Some updates/fixes on this are coming soon.
Also, I should close this issue and keep all the battery-related discussions in the other thread (#853). Thanks everyone for your feedback!
