### ISSUE TITLE
Seen/Read and Last Seen options

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1655]
## The problem

Right now we get "Sent" and "Delivered" tags, but every other app out there has "Read" or "Seen" tags too.  Can we get those?

Also, would be nice to see when someone is active or when they were last active.  Again, pretty much everything else has that.  Of course, with the ability to turn that off.

## Environment

* Wire version that exhibits the issue:
* Last Wire version that did not exhibit the issue (if applicable):
* Android OS version used to run Wire:
* Is this a custom firmware or a stock one:
* Mobile phone model/manufacturer:
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):

## Details

Describe the steps necessary to reproduce the problem in more details. The detailed description
will help us to fix the issue faster.

## Link to Debug logs

Create a [GIST](https://gist.github.com) which is a paste of your Wire logs, and link them here.
It is recommended to directly contact our [customer support](mailto:support@wire.com) and send the debug report by email, because it can potentially contain some private information, that you don't want to share to the public.

## How to send detailed debug report from Wire:

1. Go to Settings -> About
2. Tap "Wire swiss GmbH" 10 times
3. Reproduce your issue
4. Send the report from Settings -> Advanced -> Submit debug report
5. Go to Settings -> About
6. Tap "Wire swiss GmbH" 10 times again to disable detailed debug reports, because this slows down Wire

## Screenshots

Please attach screenshots if you consider them as helpful to understand/reproduce the issue

**Comment by metal450** [comment]
+1.

I was very surprised when I discovered this was missing, as I thought it was such an obvious/core feature of all chat services (that I'd ever used at least), that I initially didn't even look for it when comparing options. Would very much like to see Wire become comparable with all other chats in this way.

**Comment by ImAnnoying2** [comment]
I think Wire even had this feature a year ago, but it disappeared...

**Comment by TubaOrNotTuba** [comment]
No, Wire has never had the option for "Read" or "Seen".  It took them a year or more to get Sent/Delivered to work most of the time, but as has been reported in other threads, it's still broken if one changes networks during a conversation requiring Wire to be Force Stopped or the phone rebooted.

As for Online or Last Seen, Wire has never had that either when essentially 100% of other communication tools I see show this information.  Wire has spent too much time on fluff, like adding support for multiple accounts when bare basic things don't work.  It's these basic things that keep any of my clients from embracing Wire.  They'd rather use Skype for Business or WhatsApp than Wire just for pure basic functionality.

**Comment by x80486** [comment]
I hope this is implemented with a switch to turn it off. It's actually (in my opinion) the most annoying feature of almost every messenger out there.

**Comment by nenadandric** [comment]
Wire Pro has online status. But personal application should not have neither "online" nor "message read" status. Even popular messengers have some bugs, so sometimes even if you turn this option off, it will show your contacts if you are online. So the most secure way to ensure **user's privacy** is to not implement any of these. If you need an urgent answer, you can make a call. Also, if your message is delivered, you know user is/was online, or at least some of his devices

**Comment by metal450** [comment]
>>Even popular messengers have some bugs, so sometimes even if you turn this option off

The solution is better testing & fixing the bugs, not eliminating features.  This is an absurd argument.  It's like saying "sometimes car radios malfunction, so cars should not have radios." Or "sometimes javascript leads to vulnerabilities, so browsers should not have javascript."  No.  Users can disable these options if they want privacy - if there are bugs in the ability to disable it, that's a different issue altogether.

The most secure way to ensure **user privacy** is to have well-tested, open-source code & a community of users committed to finding, reporting, & patching issues.  Not omitting commonplace features that you personally don't want.

**Comment by nenadandric** [comment]
And that is one of the reasons why I choose Wire over Signal :)

Well, people who are really concerned for their security and privacy do disable javascript in their browsers :)

Yes, it could be implemented better, but again, this is anti-privacy feature. And Wire is privacy oriented messenger. Unlike car radio, which has nothing to do with car's main purpose (transport). Even if it is opt-in option, users might be pushed by someone to use it, against their wishes.

So in my opinion, this could be enabled only in Pro version, since in corporate environment, users need to follow guidelines made by someone else. And if someone wants it for private usage, they are free to pay the Pro subscription.

**Comment by nenadandric** [comment]
Wire has also another bugs, but in its core feauters. "Read receipt" and "online status" are not core feauters and you can have great IM without those. But nevermind, we can skip this bug argument.

But just because this feature became standard in IM world, it doesn't mean that is the best approach. Especially for privacy-focused product. Also, in other messengers, you can read a message in notification, so even if it's read, sender will not have this info. I.e. if you (or wire team) wants to have this option, maybe you need to re-think of its implementation and approach.

Why don't they make something like “silent ping” option in conversations window. So when you read a message, you can tap it and sender will get info you read it (and all the previous messages). And that's it. So receiver will have an option to choose when he will “read” the message.

**Comment by nenadandric** [comment]
Reading through notification is a good thing. It allows you to read a message without notifying sender it is read. And what is more important, it allows you to read it without opening wire app (or any other IM). The other thing is, if I leave Wire window active on my PC, but leave the room, sender will get the info I read the message, even though I didn't. That's why I say this implementation is not good (enough). It can easily provide false information to the receiver.

So there's a possibility for making better product. Maybe instead of (or next to) "@", they can put "mark above messages as read" symbol. So when you open conversation but don't want (have time) to respond, you can easily notify sender you read his messages.

But according to this
https://github.com/wireapp/wire/issues/66
Wire team is already working on the feature, and will probably make it the same as all the others

**Comment by TubaOrNotTuba** [comment]
So first, with all due respect and I'm really not trying to be a jerk here, it's not really our fault if someone leaves a secure msg'ing app open and front and center on a PC.  That's basic security.  That said, Wire could code their desktop app to not show msgs as read unless a user actually interacts with the desktop application, mouse click typing, etc...

Please remember, no one here is asking Wire to make this a requirement or even on by default, but there are many of us that would like to see this feature and given msg'ing apps like WhatsApp with something like a [1.5 billion active users](https://techcrunch.com/2018/01/31/whatsapp-hits-1-5-billion-monthly-users-19b-not-so-bad/) have this feature, they have to be doing something right.  If people didn't want this feature 1.5 billion users can scream pretty loud.  Interestingly, WhatsApp has this feature on by default, though it's easy to turn off.

**Comment by ArchiveBase** [comment]
### Let's make this clear.

Wire Pro https://support.wire.com/hc/en-us/articles/115005878949-Pro-How-can-I-let-my-team-know-if-I-m-available-busy-or-away-
Wire already has "Read Receipts" feature on desktop/android etc clients and it display with read timestamp. 

![untited](https://user-images.githubusercontent.com/46082456/52909024-885f6a00-32b3-11e9-86a1-2c59cdcd8b41.png)
Require enable through settings. Thats great.

------------------------------------

#### So what about Last Seen/ Online status?
Basically read or include read timestamp reveal about user online status. isnt?
_**we want them because of family, partner, close friend but wire team dont like because of privacy. how to solve this?**_

![screenshot_2019-02-17-11-30-50](https://user-images.githubusercontent.com/46082456/52909369-248c6f80-32ba-11e9-9794-4f8382550226.png)
(above image current telegram android version. same applied to telegram desktop)

--------

#### How enhance this facility on Wire?

-------

  _**First cover wire requirement**_
 **Online/Last Seen**
+ Keep wire last seen/ online status - no body only. that means wire will not show anything on status area (atleast doesnt know last seen recently, week else). To clear just no status **(Development)**
- Do not add easy options as "my contacts" "everybody"

**Read Receipts with timestamp**
+ Disable read receipts option on settings. no one can see **(Already available)**

-------

**_Now cover our requirement_**
**Online/Last Seen (with timestamp)**
+ Add exceptions option to wire. so we can add manually necessary users then they only can see it **(Development Request)**

**Read Receipts with timestamp**
+ Now if enable read receipts option on settings. everyone can see read status with timestamp basically that broke wire team expected privacy **(Development Request)**
 
+ Add exceptions option to wire. so we can add who should see messages read status **(Development Request)**

**We everyone waiting for experience better Wire!**

**Comment by Mikaela** [comment]
> Wire already has "Read Receipts" feature on desktop/android etc clients and it display with read timestamp.
> Require enable through settings. Thats great.
> Disable read receipts on settings. no one can see (Already available)

I am coming from https://github.com/wireapp/wire/issues/66 and it seems that this is only the case for 1:1 chats, while group chats are missing the read markers. I think they would be an important feature for my family or their lack would be noticed as we move from WhatsApp to Wire.

The situation also seems to have changed a bit from your comment as currently I see an eye symbol with the read timestamp.

**Comment by makingthematrix** [comment]
Both read receipts and availability statuses are currently implemented in Wire, but they're not available in the free version. That may change in the future.
