### ISSUE TITLE
why scala？

### ISSUE THREAD

**Issue by huijimuhe** [wireapp/wire-android#19]
first,great work!
but I don't understand,why using scala?
Is there any benifit using it?
could anyone explain?
thanks!

**Comment by zbsz** [comment]
That's not the best place for this kind of questions.
We chose Scala because we could, because it works, and we like it :)
There is no hard reason for that choice, you could write it in plain Java if you like it. 
It mostly boils down to personal preference, we choose the tools that we believe are good for the job.
I like Scala because it's concise and powerful, it let's us write less code with better type safety, meaning much less bugs.
You could always argue against that choice, but you would not convince me :)

**Comment by huijimuhe** [comment]
i think you must misunderstood me(english is not my first language).if any inconvenient,apologize.
i just never saw a project using scala before,so i was curious.
i google some docs and blogs explained the grammar and background,bu not in detail.
like you said it's a better choice for handing audio and video calls,i was thinking it's a tool like dagger2.
thank you for explaining the why and how using scala.
