### ISSUE TITLE
No Internet Connection with MicroG on Kitkat 4.4.2

### ISSUE THREAD

**Issue by davidicharp** [wireapp/wire-android#1923]
## The problem

Using both the recommend MicroG Service Core 0.2.4-81 for Kitkat or the newest update 0.2.6.13280 on my Samsung s4, I have no internet connection when I try to login. 

Wire runs fine on linageos 14.1 with MicroG. 

## Environment

* Wire version that exhibits the issue: 3.24.681
* Last Wire version that did not exhibit the issue (if applicable):
* Android OS version used to run Wire: Kitkat 4.4.2
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: Samsung S4 I9500
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi & LTE

**Comment by davidicharp** [comment]
I forgot to mention that when I use google play services that Wire does see an internet connection using Kitkat.

**Comment by marcoconti83** [comment]
Hi @davidicharp ,

Thanks for opening the issue. When you say that you have no internet connection, does it mean that you get a banner or a popup informing you that there is no internet connection, or that simply the operations never complete?

**Comment by davidicharp** [comment]
I get a popup saying there is no internet connection. 

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Feb 12, 2019, 6:35 PM by notifications@github.com:

**Comment by marcoconti83** [comment]
Hi everyone,

since last public version, Wire dropped support for Android 4.x. This is due lack of resources necessary to keep creating custom solutions for Android versions that are 5 years old, and inability to enforce certain security policies on those versions. I understand that this is a loss for Android 4.x users, but I'm afraid we won't be able to go back on this decision any time soon.

The lowest supported version is now officially 5.0.
