### ISSUE TITLE
help extract camera into standalone project 

### ISSUE THREAD

**Issue by madibalive** [wireapp/wire-android#193]
Hi , currently in the process painstakingly extraction the camera module into a standalone, i realized the library and files are spread across , am in rewriting parts that have tight coupling 
Has anyone tried this and or can direct me in the right direction , any help would be appreciated ??

**Comment by deanrobertcook** [comment]
Hi @madibalive, the best way would be to extract `GlobalCameraController.scala`, `CameraPreviewTextureView.scala` and `CameraPreviewObserver.java` into a separate module/project. The trickiest part would be to get the dependency injection working, but for a quick prototype you could just have a singleton `GlobalCameraController` created in your app, and when you construct a `CameraPreviewTextureView` just find that singleton and use that instead. 

The `PermissionsController` is only necessary if you want to handle Android M permissions, so you can probably remove it and just execute the blocks of code in its methods directly.

The other thing you would need as well is the `CancellableFuture` class from our [SE](https://github.com/wireapp/wire-android-sync-engine) project, but that has only taken me about 10 minutes to do in the past, since it's pretty isolated from everything.

Once you have all the dependencies sorted out, it's just a matter of placing an instance of `CameraPreviewTextureView` somewhere into your view hierarchy and adding a listener to it.

I hope that provides some high-level guidance. There are of course things I'll have forgotten about, but let me know how it goes. This is something I'd also be interested in doing myself, if I had the time :)

**Comment by aftabsikander** [comment]
@deanrobertcook  I am looking into this myself in process of making a standalone project for camera and video feature. A quick question why **CameraPreviewTextureView** and other camera related classes are written in **scala** any special reason.

**Comment by aftabsikander** [comment]
@madibalive Were you able to extract camera module into a standalone module. If do can you please share link.

**Comment by marcoconti83** [comment]
Hi all,
it has been 3 years since the last comment on this thread. I will close the issue as I assume it's not relevant anymore. Feel free to reopen if you have more questions!
