### ISSUE TITLE
[Feature Request] Setting to request incognito keyboard

### ISSUE THREAD

**Issue by Don42** [wireapp/wire-android#1945]
## The problem

Keyboard personalized learning might leak message content. So some apps (Signal, Chrome Incognito, ...) request an incognito keyboard, which deactivates the personalized learning feature. 
This might not be relevant for all users, but it is helpful in preventing information leaks from an 
encrypted chat.

- [How-To](https://www.xda-developers.com/api-apps-keyboard-incognito-mode/)

**Comment by marcoconti83** [comment]
Hi @Don42 ,

thanks for the suggestion. It makes sense, however I am not sure when we will be able to pick this up. We will keep it in mind for the future.

For the time being, if anyone from the community would like to give it a try, this sounds like something that is well suited for an isolated PR. We'd be happy to give some pointers.

**Comment by harishvishwakarma** [comment]
@marcoconti83 I have done it on another application. Won't mind doing it here too.

**Comment by marcoconti83** [comment]
Hi @harishvishwakarma,

That's great, thanks for looking into this.

This change can be broken down in the following incremental steps:

- Set up and compile the project locally
- Modify the layout of the "Options" screen to add a "Use incognito keyboard" in the "by popular demand" section. Try to find the layout XML for the options screen and add the proper text and switch there. You can copy-paste from other similar element in the XML, to make sure that it uses the proper classes and IDs structure.
- Read/store the value of the setting in the persistent store for user settings
- Use the setting to modify the keyboard behavior when the keyboard is brought up

Let me know if you get stuck on any steps and I can give you more details.

**Comment by marcoconti83** [comment]
FYI @jennifergoertzen

**Comment by harishvishwakarma** [comment]
@marcoconti83 I see that Preferences.scala is read only so I cannot add the preference there.
 There are 2 question:
1. How can I add a preference with Preferences.scala as read only
2. Why is Scala widely used in the project? Any useful read that would tell the benefits of it?

**Comment by marcoconti83** [comment]
Our Android application is written (almost) entirely in Scala. Going forward, we will start moving at least the UI part to Kotlin, but that's a large project and we are not ready to start yet.

The application is split in two:
- The app, which implements the UI layer: https://github.com/wireapp/wire-android
- a synchronization/caching/logic layer, called "Sync Engine": https://github.com/wireapp/wire-android-sync-engine

`Preferences.scala` is part of the Sync Engine layer. In order to make changes in the SE, you need to check out and open that project. You can find a README on that repo that explains how to make a local build with your modifications and include your local sync engine in the locally compiled app.

**Comment by harishvishwakarma** [comment]
@marcoconti83 How can I test changes on Sync Engine?

**Comment by marcoconti83** [comment]
Hi @harishvishwakarma ,
There are two ways to test (and if applicable, you should try both):
- unit tests: run `sbt test`. If you only want to rerun one test instead of the entire suite, you can run `sbt testOnly *<nameOfTest>*` where name of test is the name of the test class (e.g. `*UserSyncService*`.
- Manually verify on device. You can build a local version of Sync Engine and then use it in the UI project. See [instructions in the README](https://github.com/wireapp/wire-android-sync-engine#building)

**Comment by marcoconti83** [comment]
FYI @raphaelrobert

**Comment by harishvishwakarma** [comment]
@marcoconti83 Hi there. I didn't try much on this issue till yet. I re-read the instructions today and planning on taking this over the weekend.
Will keep you guys informed.

**Comment by marcoconti83** [comment]
Hi @harishvishwakarma ,
We will start working on this issue ourselves, as this feature is now part of our roadmap. Thank for your interest in helping! We will take over the development of this feature, but there are still plenty of [external contributors-friendly issues](https://github.com/wireapp/wire-android/labels/external%20contributors%20friendly) if you still want to contribute.

It's worth noting that in the meanwhile we simplified our build process a bit, so now Sync Engine is part of the main project, and you don't need to publish the library locally for local development. So the project in this repo is the only thing you need to develop.

**Comment by marcoconti83** [comment]
Hi all,
this has been released in version 3.42.
