### ISSUE TITLE
Long audio pauses eventually resumed with no audible indication that session is still active

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-android#1970]
## The problem

During a Wire audio call between two parties, audio blanks out for long periods of time, as much as 1–2 minutes. Shortly after audio blanks out, a few fast beeps are heard, then only silence. While the audio is blanked out, the display shows the call still in progress. Most of the time, the audio will eventually resume. Some of the time the audio never resumes, but the connection still shows as active, so the user has to manually disconnect then redial.

## Environment

This has been observed on several Android devices at my end during the past 12 months or longer. At my end, it was most recently observed on (a) a stock Galaxy Tab S2 tablet running Android 7.0 and Wire 3.26.694 and (b) a stock Moto X4 running Android 9.0 and Wire 3.26.694. These devices were always connected to reliable Wi-Fi. I have been communicating with several different people using both Android and IOS devices whose exact models are unavailable (but probably not relevant).

## Details

There are two slightly different issues here.

First, the fact of the long audio gaps. At least in some of the cases, devices at both ends were connected to reliable Wi-Fi. So it's unlikely to be a network issue. More likely the Wire infrastructure itself is producing the long silences. A similar problem seems to have been reported in Issue #1405.

Second, during the long pauses, there was no indication to the user that audio will eventually resume. So I was not sure whether I should patiently wait or disconnect and redial.

The question of comfort noise was brought up in Issue #754, and the developers responded: 'Our approach to signal users that a call is up or has gone down is by playing audio notifications. Otherwise reliability should be just so high that the question "are you still there" is not needed.'

Both of these points appear to be not currently applicable. I.e., (a) no audio notifications are available that tell the user to keep holding rather than disconnecting and redialing, and (b) audio call reliability is not always high even over Wi-Fi.

I have not attempted to collect debugging logs. However, if the developers are not already aware of the reasons for this issue, I will be happy to create and provide debugging logs upon request.

**Comment by marcoconti83** [comment]
Hi @fortran77 ,
this sounds like an issue somewhere. If the audio is not flowing because the connection failed, the app should play a "blip blip" sound to let you know that the audio is interrupted because of the connection.

The only cases in which you should hear silence are:
- the call is working fine and no one is talking
- the other side muted the microphone
- the other side has some issues with the microphone

If you can pull the logs for this situation, it would help shed light on the issue. 
Thanks!

**Comment by fortran77** [comment]
Thanks, I will collect a debugging log as requested. (It may take some time.)

**Comment by marcoconti83** [comment]
Hi @fortran77 ,

we had a look at the logging facility in the past couple of days and it looks like the logs that we need are currently disabled for production builds, due to privacy concerns (we don't you to accidentally send us log with private information in it). We are in the process of sanitizing those logs so that they are private enough, but it will take at least a couple more weeks. If you have a production build today, you won't see any meaningful log at the moment.

The only option for the moment is to build the client on your own, but I'm not if sure that's an option for you?

**Comment by fortran77** [comment]
You are right to be concerned about privacy.

I am actually using Wire successfully. The people I talk with knows that these long pauses occur, so we just wait patiently, and redial if necessary. While I could in theory build the client, it would be a long process as I would have to begin by installing all the needed tools. I'll just wait until the time is right and the production builds will give you the needed logs.

**Comment by selurvedu** [comment]
I am hit by the **exactly** same two problems. I'm glad that this is not an issue that is unique to me, so this is probably not a problem on my side.

> Shortly after audio blanks out, a few fast beeps are heard, then only silence. While the audio is blanked out, the display shows the call still in progress. Most of the time, the audio will eventually resume.

On older versions of the Wire Android client, the (very annoying!) "blip blip" sound used to loop indefinitely until the call recovered. It stopped doing so some time ago. I am not sure when, but I definitely can say that the problem was present in December.

> Some of the time the audio never resumes, but the connection still shows as active, so the user has to manually disconnect then redial.

This problem was present since I started using Wire on Android (that was in February 2018 or so).

JFYI, my ROM is LineageOS. I use Wire APKs from Google Play. The problems persist both with and without microG (never tried with Google Play Services though, but I doubt it would help).

**Comment by fortran77** [comment]
Lately I have been using Google Duo for end-to-end encrypted voice calls. Because I can hear the other person :-).

I still find Wire useful for text messages and attachments. I do hope they have enough funding to solve the problems in the long run.

It's very unfortunate but there seems to be no good end-to-end encrypted application in existence. Wire keeps blanking out audio and sometimes disconnects; Signal requires disclosure of mobile phone number and won't work on non-SIM tablets and voice quality is not usually good; Google Duo is not open source, even though it's unlikely that Google is snooping on call (yet), and requires disclosure of mobile phone number; WhatsApp although allegedly end-to-end encrypted is in the custody of Mark Zuckerberg (need we say more?) and requires disclosure of mobile phone number; and all the others are almost certainly subject to snooping by their respective service providers.

**Comment by marcoconti83** [comment]
Hi all,
we now have proper logs in the public build. Sending those logs would help us understand where this issue is coming from. You can send the logs at support@wire.com, and please **put the `[LOGS]` tag** in the subject of the email.

**Comment by Gardosen** [comment]
as there was no response on this for the past 10 months, and the calling system has been evolved a lot over the past year, i close this now.

if someone still has such an issue, he is free to reopen another issue and let us know about it in more detail with information based on the current client.

Kind regards
Marco

**Comment by fortran77** [comment]
I would have very much liked to submit debugging logs. However, I have had difficulty using Wire for audio calls because too often a called party's phone does not ring at all, or sometimes rings just once or twice. It's hard to get other people to use Wire for audio calls if they don't hear ringing, or if you don't hear ringing when they call you. At one time in the past the failure to ring was sporadic, but then it became quite consistent.

So my correspondents and I migrated to mostly using Google Duo for end-to-end encrypted audio calls. Also sometimes we use WhatsApp or, less frequently, Viber. All of these applications always cause ringing at the other end, while Wire rarely does.

Other relevant issues: #723, https://github.com/wireapp/wire/issues/202

I still find Wire somewhat useful for text messages. But on both Android and IOS devices, Wire does not always cause a notification for the recipient. So Wire is not as useful as it could be. All my correspondents find WhatsApp reliable and Wire not so much.
