### ISSUE TITLE
Feature request: persistent notification

### ISSUE THREAD

**Issue by Mikaela** [wireapp/wire-android#2153]
**Describe the bug**

I am not getting notifications from Wire at all, especially if I have rebooted my phone. I wish Wire had an option to show notification all the time in the statusbar (like Conversations) saying it's online/offline, so I at least knew it was running.

**To Reproduce**

N/A or reboot your phone and receive a message and see no notification. Alternatively open settings and look for persistent notification and see that there is none.

**Expected behavior**

I expected to receive notifications shortly or to find an option in settings to enable persistent notification.

**Screenshots**

N/A

**Smartphone (please complete the following information):**

- Wire 3.33.786
- Android Go 8.1.0 (1 April 2019 security patches)
- stock firmware (but with [com.evenwell.emm removed](https://dontkillmyapp.com/nokia))
- HMD Global TA-1047 (aka Nokia 1)
- LTE (always fconnected enabled in network settings) + Wi-Fi

**Additional context**

I am bringing my family over to Wire from WhatsApp as you seem the best option.

**Comment by marcoconti83** [comment]
Hi @Mikaela ,
thanks for opening the ticket. If I understand correctly, you are suggesting to implement a workaround for the fact that you are not receiving notifications. We are tracking all notification issues here: #777 and I'd rather continue to investigate how to address the issue rather than add a new feature as a workaround. I'm closing this issue now, please continue the discussion in #777. Thanks for your patience!
