### ISSUE TITLE
[feature request] make it easier to verify fingerprint

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#217]
Right now one has to read the whole string and it can be a little hard. Maybe scanning a qr code would be better?

**Comment by bjoernherbig** [comment]
We are discussing improvements to the verification. We have some ideas on how to, but no timeline yet.

**Comment by Be-ing** [comment]
Having multiple options would be great. I think QR codes, NFC, and Bluetooth would all be good options. QR codes would probably be the easiest and most reliable across different hardware, but some hardware may not have a (functioning) camera. Not all smartphones out there today have NFC, although Bluetooth is quite ubiquitous and quite widespread in laptops & desktops.

Ideally, these in person information exchanges could be used so that users don't have to bother exchanging phone numbers or email addresses either. They could add each other as contacts in Wire and verify their devices simultaneously.
