### ISSUE TITLE
Farewell: Value Missing

### ISSUE THREAD

**Issue by CeryleRudis** [wireapp/wire-android#2275]
I bid Wire farewell.

Continued issues that have been listed as closed are still an issue, open tickets don't really seem to get any attention. Logging here or direct to support does not seem to help the cause of getting wire working, I am not the only one experiencing this, this occurs across varying android os versions, ios, etc.

There is unfortunately no value to achieve to become a paying customer, so I am not sure how they get around this for those that do. Base level functions that are expected of any messaging client just continue to be a problem, Notifications, message receiving, for example. There is no general connectivity issue, other messaging clients work fine to the same contacts.

**Comment by marcoconti83** [comment]
Hi @CeryleRudis ,
Thanks for the honest feedback. 

We are sad to see you go, and we hope to improve on the issues you mentioned, so that you will consider giving Wire another try in the future.

On the practical side, it's easier to track individual issues on separate tickets that refer to one issue at the time, so I will close this one.
