### ISSUE TITLE
What's difference between Assets and Assets2 in android_wbu?

### ISSUE THREAD

**Issue by CroneG** [wireapp/wire-android#2323]

**Comment by marcoconti83** [comment]
Hi @CroneG ,

The Wire backend protocol supported various versions of assets in different versions. Up until 2017, Wire was using version 2 of assets, which were tied to a conversation. From 2017, we started using version 3 of assets, that are not tied to a conversation at all. Since we don't want users to lose the assets that they sent with previous versions, the Android application provide supports for both version 2 and version 3 (version 1 was discontinued a long time ago).
