### ISSUE TITLE
Impossible to know who is a contact with pseudo

### ISSUE THREAD

**Issue by ElucGeek** [wireapp/wire-android#248]
I have a new contact in my Wire contact list, it's pseudo is random (like abcde) and his picture is a landscape. How can I know who is he from my address book ? Can I see his email or phone number ? There should be an indication telling me from where I got the contact (i.ie manually added, linked from my address book, discovered from my email, discovered from my phone number).

**Comment by bjoernherbig** [comment]
acknowleded. we are planning improvements to this soon. no timeline to share yet though.

**Comment by h-2** [comment]
I have stated in this also in #317 

But just to give more explanation:
It is not only about people that I don't know, but it is also confusing if I actually know the poeple, but they didn't enter their full name or a nickname. E.g. I am told that Bob uses Wire, but I have 5 different Bobs in my address book.
That is precisely why integration with the address book is good, if I give someone the name "Bob (friendly guy from Debian)" in my address book than it should show up as "Bob (friendly guy from Debian)" in Wire and not "Robert Johnson" which I have no clue about. 

I would also propose this for user pictures, at least in the cases where there is a user picture in my address book. This is a huge recognition factor on my device, because the image is used in my e-mail program, my sms-program, Kontalk, Signal, Conversations...

**Comment by IpsmLorem** [comment]
Linking to the adress book should be optional. User should be able to choose local name and picture if they do not want to risk contact book leakage and still have the ability to have a clean/usable contact list.

cf. https://github.com/wireapp/wire-ios/issues/208

**Comment by someoneEsle** [comment]
Although the last update brings usernames and allows details fetched from the address book to be displayed (when tapping someone's name within a conversation), I would still say that Wire needs to go one step further and *always* prioritise the names fetched from the address book -- both in the conversations list and in the people list.
This is especially important when forwarding something, for example. Right now, having the address book's details hidden behind a few taps after opening a conversation does not help telling who is who while forwarding.

**Comment by gilshwartz** [comment]
I would suggest to simply add a nick property to a contact, which by default is the same as the contact's name. However, a user can locally (for his or her own personal use) change the nick and the contacts list will use the nick for display, rather than the contact's name.

**Comment by n3niu** [comment]
I agree that this feature would ease identifying contacts from address book in Wire. However, the Wire user's anonymity should always be preserved with highest priority. It might be not reasonable from a privacy point of view if an anonymized Wire user name is replaced by an identifiable denominator e.g. the contact's clear text name by the user. Please consider adding a configuration option how Wire deals with the Wire user's identity.

**Comment by gilshwartz** [comment]
Well, as long as the nick is private to the user using it in his or her private wire address book, there is no privacy issues (anyway, all address book info should be encrypted per the user owning the address book). If the contact is truly anonymous, any nick will do and will not violate privacy. If the user knows the contact, the contact is not anonymous anyway so the nick is just a convenience.

**Comment by grinapo** [comment]
Two thoughts - for both ends. 

First, me as the person would like to be able to share some info on me, to distinguish, to identify, you name it. Name and nick is obvious, but I would share an "about me" oneliner to make it sure it's me without revealing the identity. (And technically I would rather avoid my avatar being used as my own background. I'm not _that_ narcisstic. A plain color would even do just fine.)

As for my contacts I would like to rename their visible name to what I like, while obviously retaining all the info they chose to share about themselves. (Apart from duplicates and random names I have a few contacts with asian characters or non-displayable characters name. Highly meaningless and user unfriendly.)

**Comment by grinapo** [comment]
Would be nice to rename this issue: **change contact name or set local contact data**
Also would be nice to acknowledge the high amount of duplicates and agreements by honouring this issue into the roadmap. ;-)

**Comment by 2114L3** [comment]
as others have mentioned; this problem comes about because profile name and username is searchable (aka public). i would not need this feature if profile name was private to approved/added contacts (less otto) 

i disagree with wires support page classing other wire uses as not being public.
https://support.wire.com/hc/en-us/articles/203763040-Who-will-see-my-profile-name-or-username-displayed-in-Wire-

**Comment by taohansen** [comment]
Please add this feature. It is so so simple.

**Comment by makingthematrix** [comment]
Currently something like this feature is available to business users: a separate account which can't be found with public search. We mat consider to release it to public in the future.
Currently there are no plans for local usernames.
