### ISSUE TITLE
using android app with demo-server

### ISSUE THREAD

**Issue by yuan9778** [wireapp/wire-android#2538]
I have successfully installed and run a demo-server using the instructions at: https://github.com/wireapp/wire-server

I want to use this demo-server instead of the server at wire.com as my server . What should I edit in this project? I edited default.json file of this project as shown below and rebuilt the project:
`"backendUrl": "x.x.x.x:8080",
  "websocketUrl": "x.x.x.x:8081",
  "teamsUrl": "x.x.x.x:8085",
  "accountsUrl": "x.x.x.x:8082",`
x.x.x.x is my demo-server IP.

I created a regular user using ./create_test_user.sh in the demo-server and tried to log in with it on my android app.  It stucked at the login step and I didn't see responses in the terminal that is running the server.
I'm new in android programming.  I really appreciate it if someone shed some light on this.

**Comment by Gardosen** [comment]
Hello @yuan9778,

i apologize for the late reply, but i sadly have to tell you that there is no support on such topics.
the dev team is always trying to make the usage of the repositories as easy as possible, but there is a certain amount if knowledge required in order to setup the system and maintain it. 

we clearly have not the resources and capability of supporting such a request.

There for i will close this ticket now to clean up the issues board.

Kind regards
Marco from the Android Team
