### ISSUE TITLE
Sending message freeze the app for about 20-30 seconds

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2566]
Message is a short sentence, It happen in phases, seems to fix itself after a restart.

**Comment by Gardosen** [comment]
Hy @Transisto ,

could you please provide us more information about your phone and the wire version you are using?
in order to be able to investigate about such issues, as much information as possible is helpful to be able to reproduce it. 

What Android device(manufacturer and model)?
What Android OS?
Is the Phone rooted?
What Wire Version?
Does this happens just recently with an update, or always?

Kind regards
Marco from Wire

**Comment by Transisto** [comment]
Phone is S10+ and is not rooted.

Using latest OS version with latest Wire version.
It doesn't happen often but happened no later than yesterday.

The phone is doing nothing and the message takes almost 30 to send. (wire frozen for 30sec)

**Comment by Gardosen** [comment]
Hey @Transisto ,

thanks for the information, one side question, does this scenario happen when you just recently opened the app or when it is open for quiet some time?
also, does this happen for you on wifi and mobile connection, or only one of them?

Kind regards
Marco from Wire

**Comment by makingthematrix** [comment]
Please re-test with the new release (3.46). OkHttp was updated - with some of the last releases they made sendind data more reliable - and we made some changes to Wire Android which could result in the app's reacting faster.

**Comment by makingthematrix** [comment]
Ok, I think we can close this issue now.
