### ISSUE TITLE
Initiating a video call always uses the internal speaker

### ISSUE THREAD

**Issue by boldt** [wireapp/wire-android#270]
My device: Sony Xperia Z5, Android 6.0.1, Wire 2.18.288

If I do a **non-video-call** I have three buttons (I have a German version, so I'm not sure about the correct english terms): 
1. Mute (Stummschalten)
2. Hang up (Auflegen)
3. Speaker (Laustsprecher)

If I do a **video-call** I have just two buttons: 
1. Mute (Stummschalten)
2. Hang up (Auflegen)

The Speaker option **does not** exists. 
### I have the following issue:

If I **initiale** a video-call, the sound always uses the internal speaker. I am not able to change it to the external speaker duing the connection, and not  during the call.
#### My current workaround:

Doing a non-video call. Enabling the speaker. Do a video call.

If I **get** a video-call, it always uses the external speaker. There is no way to change this.

**Comment by someoneEsle** [comment]
What device are you on, and which Android version?

**Comment by boldt** [comment]
My device: Sony Xperia Z5, Android 6.0.1, Wire 2.18.288

**Comment by tokariu** [comment]
I want to add that the same or similar problem exists for a Samsung Tablet.

Tablet: Samsung Galaxy Tab A
Model: SM-T550
Android: 6.0

If the tablet user gets a voice or video call, he cannot hear what the opposite is saying, because there is simply no sound at all. The mic is working, though - the opposite is hearing what the tablet user is saying. video just works fine - just no sound from the opposite.

I guess Wire for android always automatically tries to use the internal speaker (the one for the ear on a smartphone). However, on the tablet there is no such internal speaker, only an external speaker exists. therefor the tablet user doesn't hear anything and there is nothing one can do about it.
The sound in other apps (skype, whatsapp, youtube) just work as expected. So it gotta be a bug in Wire..

**Comment by david-wire** [comment]
We haven't been able to reproduce on our side as this seems to be a device related issue (some devices do have this issue, others don't). We will need to investigate further.
Meanwhile, the latest version of the app being 2.24.303, please let us know if you have additional findings to share.
Thanks!

**Comment by tokariu** [comment]
@david-wire just a little update: the problem still exists in the recent version with the Samsung SM-T550 tablet.
But we found out that the sound is working with headphones. This is interesting because it means Wire always tries to use the sound-output of the headphone by default instead of the tablet's speaker. Skype however detects that there is no headphone and correctly uses the tablets speaker. That's where Wire currently fails.

**Comment by alien2003** [comment]
The same on Xiaomi Redmi Note 3 Pro, Android 6. Can't do proper video call in headphones.
Also Wire ringtone ignores Viper's Audio maybe it's related. Sound is always poor even with "speaker optimization" enabled in Viper

**Comment by idlewan** [comment]
Present as well on the Nvidia Shield Tablet K1 on Android 7.0, no speaker button to be found, even when starting an audio call.

**Comment by jomajojo** [comment]
Moto G 5 S plus
In Video calls there is only the internal speaker working

**Comment by juliss95** [comment]
Me and another person have a similar problem.
When starting a video call with headphones in the phone, Wire still uses the speaker. We now have to start, take the headphones out and put them in again to get sound through headphones.

**Comment by shiv0611** [comment]
I am using MI Note 3 and while using WhatsApp video call it's only using internal speaker, it's detecting my headphones.

**Comment by Gardosen** [comment]
I tested this issue on our recent build and could not verify it.

if this issue still exists for someone, he is free to open another issue ticket, to keep track of this with the most up to date information in order to reproduce this.

Kind regards
Marco from the Android Team
