### ISSUE TITLE
Backup conversations now won't let you not set a password

### ISSUE THREAD

**Issue by mgrandi** [wireapp/wire-android#2708]
**Describe the bug**
Before, you were able to backup conversations and just not provide a password to have a plain sqlcipher database with no password, it seems that broken in a recent update

possibly related to: https://github.com/wireapp/wire-android/pull/2474

**To Reproduce**
go to settings -> account -> backup conversations

see dialog that prompts to set a password

click "OK" without typing anything in the box

see it warning about password requirements, and also not able to continue pass this dialog

**Expected behavior**
be able to export the backup without a password

**Screenshots**

![Screenshot_20200322-162137](https://user-images.githubusercontent.com/802786/77265734-b7849f80-6c5a-11ea-8c8c-b44b64a7faea.png)

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue:

 3.46.890
- Last Wire version that did not exhibit the issue (if applicable):

not sure on the version, but the backup i made before this was on march 3rd 2020 and did not have this problem

- Android OS version used to run Wire:

10

- Is this a custom firmware or a stock one:

stock

- Mobile phone model/manufacturer:

google pixel 2 XL

- Mobile network type (EDGE/LTE/Wi-Fi/Offline):

Wifi

**Comment by makingthematrix** [comment]
@mgrandi : The password is required by design now. We still allow for restoration of backups which were made previously without any password.

**Comment by robert-reinhardt** [comment]
Dear designers - those that have now made the password required by design - you are simply rude and inconsiderate. Not to mention that this fundamental change of behaviour is not documented in the release notes.

Use cases for the backup file can be quite different: the backup file is the only way to get any information out from wire to the external world. In the lack of any decent **text export functionality** (and also media export functionality, but this is another problem) I have made a python script that exports a conversation from the backup archive.

This is now broken since somebody thought he is smarter than the wire users.

There were very clear warnings for doing backup without the password and it was up to the user to decide about the risks. The statement still reads: "_The backup will be compressed, and **if you set a password**, also encrypted. Make sure to store it in a secure place._" If not for anything else the bug should remain open to fix this text that gives false hope that you are able to make a password-less backup.

I think the least you can do is to provide a utility to decrypt the backup when at a safe location. Or at least decently document how to do it. Of course, I can peek at the source, but for that matter, I could also write my own messaging system that will be exactly as I want it. Unluckily, I cannot do the same with all the software that I use and wire-like functionality is not the most important part of the software I use.

As V3.46 also broke some other things I am looking at the wire-exit plan: I now have a 16MB wire database that seems to be endangered by some whimsical ideas of wire developers.
