### ISSUE TITLE
Fixed APK download

### ISSUE THREAD

**Issue by kausban** [wireapp/wire-android#2934]
Hi is there a *fixed URL* to download the latest APKs from the wire website or published on github? 

The naming is never consistent (its currently 3.50.**922**.apk) so its hard to maintain one's own fdroid repo for example. The current apk is already 2 releases behind BTW: https://wire-app.wire.com/android/prod/wire-prod-release-3.50.922.apk

**Comment by makingthematrix** [comment]
Hi @kausban,

We use that last number in the version to differentiate among different release candidates. If you want to maintain one link to the current release, I'm afraid you have to generate it based on some pattern matching.

I maintain a small archive of our apks and maybe there's a way I can help you by putting the link to the current release somewhere there in a way that you can retrieve it with a script, but that's an unofficial archive. I can't guarantee it will be always up to date.

And thanks for pointing out the link at the webpage is outdated.

**Comment by kausban** [comment]
Thanks for the response, @makingthematrix . 

I understand that the last numbers are the release candidate label. Would it be possible to tag the releases with the correct RC number as well? I can then pull the right version from "https://api.github.com/repos/wireapp/wire-android/releases/latest" (see: tag_name)

> I maintain a small archive of our apks and maybe there's a way I can help you by putting the link to the current release ...

That would be much appreciated. Are the checksum of the latest binaries published somewhere on the wire webpage or git repo to verify the unofficial repository?

**Comment by DC7IA** [comment]
This would really be a nice feature to have.

**Comment by maltfield** [comment]
I'm also blocked from downloading the latest version of Wire because I can't find the APK at all anymore. It does not appear to be listed on the download page from the wire.com domain

 * https://wire.com/download

I've tried to go to the corresponding GitHub releases page, but it also didn't have an APK

 * https://github.com/wireapp/wire-android/releases/latest

The above page has a `version.txt` file, which states

```
VersionCode: 2493557
VersionName: 3.78.13
Revision: bce783b
Buildtime: 03-02-2022 15:32:54
Application-name: com.wire
```

I appended this `VersionName` to the usual download link, but I get "Access Denied" (which appears to be more like a 404 from a not-very-nice CDN)

 * https://wire-app.wire.com/android/prod/wire-prod-release-3.73.13.apk

**Comment by makingthematrix** [comment]
@maltfield :
APKs are now on the release page at GitHub: https://github.com/wireapp/wire-android/releases/tag/3.78.13
We are also on F-droid, but it takes a bit to upload there.
