### ISSUE TITLE
Do not send notifications when I'm actively chatting on webapp

### ISSUE THREAD

**Issue by maximbaz** [wireapp/wire-android#3020]
While I'm actively chatting on webapp, I also receive every single reply message on my Android phone, which is lying nearby with screen off, and which in turn sends notifications to my smart watch, constantly and unnecessarily draining power from both phone and smart watch.

I would like notifications to arrive to the phone only when I am not actively using webapp. Maybe the simplest rule is that I don't read any new message on the desktop within... say 30 or 60 seconds. Or if you can detect that I closed browser / wire webapp tab / put laptop to sleep. But the simple 30 seconds rule would be good enough.

Important note about *any* message, I can be chatting with two people at the same time, and if one person replied to me while I'm replying to the second person on webapp, I still do not need notifications on my phone.

I also tried using "Maintain persistent connection to Wire server" in the app because I thought maybe having two different mechanisms at delivering notifications, but the issue is equally reproducible.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.54.938
- Last Wire version that did not exhibit the issue (if applicable): N/A
- Android OS version used to run Wire: 10
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Samsung A50
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi

**Comment by widardd** [comment]
I have to set my smartwatch to "do not disturb" when at home due to this, I like your suggestion!

**Comment by makingthematrix** [comment]
@maximbaz :
For encryption/decryption to work it's necessary that events come to the device in order. So it's not possible **not** to send an event to your phone. We discussed the possibility to delete notifications the users already received, basing on the knowledge that they were read on another device, but that proved to be too costly - Android is very strict about how much can we do while the app is in the background.

However, since the 3.78 release the notifications were reimplemented and now it should be easier to remove notifications, just opening the app make it sync with the server and notifications are removed.
