### ISSUE TITLE
App crashes when sent to the background

### ISSUE THREAD

**Issue by d-void** [wireapp/wire-android#3197]
With latest update (3.65.979) the app no longer works in the background. Pressing Back, Home or Recents will produce a crash every time. A quick peek at Playstore reviews confirms this issue.

android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=FOREGROUND_NOTIFICATION_CHANNEL_ID pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 category=service vis=PRIVATE)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:1143)
	at android.os.Handler.dispatchMessage(Unknown Source:21)
	at android.os.Looper.loop(Unknown Source:152)
	at android.app.ActivityThread.main(Unknown Source:65)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:338)

**Comment by Kyoshiro-san** [comment]
I'm having the same issue, Wire crashes when sent to background (even by shutting off the screen while in foreground). This means users having this issue cannot receive notifications of new messages, and can only use Wire as on-demand communication device.

I'm running Android 8.1.0 from LineageOS 15.

**Comment by Hnaguski** [comment]
Having the same issue on LineageOS 17.1 (Android 10)

**Comment by LibertatisPrius** [comment]
I'm having the same issue on LineageOS 16/Android 9 without GAPPS. I've tried resetting the push notification token & toggling "maintain connection to server" off & back on with no improvement.

**Comment by kausban** [comment]
Have the same bug on both my phones (Android 11 and Android 10). Was wondering why I was missing notifications since a week.

How was this a "production release" and was not caught in testing?. Is there no beta or testing involved at all?

**Comment by Maxattax97** [comment]
Recently switched phones from Samsung Galaxy S8 running stock firmware to GrapheneOS on Pixel 4a, saw same issue on both. I need it to run in the background since I can't get notifications from Google Play Services anymore (deGoogled phone).

**Comment by Kyoshiro-san** [comment]
It seems clear there is a problem with the background push notifications listener implemented for users not having Google Play Services.

The commit for 3.65 displays optimizations for this component:
https://github.com/wireapp/wire-android/compare/3.64...3.65

Might come from this PR:
https://github.com/wireapp/wire-android/pull/3180/files/04beb5449cadebf8d5b951a342de0f95d93bc800
https://github.com/wireapp/wire-android/pull/3180

**Comment by LibertatisPrius** [comment]
I would question whether this issue is exclusive to GAPPS-less phones. The Play Store has many reviews complaining that Wire is crashing constantly with the latest update. While some of those reviews might come from de-Gooogled devices, I doubt all of them do.

**Comment by Maxattax97** [comment]
Want to affirm that this issue still exists on phones **with** GApps from my previous comment:
> Samsung Galaxy S8 running stock [Samsung] firmware

My issue also happened to appear on a de-googled phone running Graphene which had no GApps.

**Comment by kausban** [comment]
> I would question whether this issue is exclusive to GAPPS-less phones. 

I have two phones. One with and one without gapps. Same problem in both.

**Comment by kreegahbundolo** [comment]
Just installed this app on a new Samsung S10 with gapps and can confirm that it crashes when put in background. Version is 3.65.979.

However, the problem seems to go way if I switch off the option for maintaining connection to server.

This was not an issue in earlier versions, so has there been some tweaks made to background permission handling?

**Comment by Kyoshiro-san** [comment]
> Does wire team read (take into consideration?) crash logs sent via [website](https://support.wire.com/hc/en-us/requests/new), if not please take a look at those from there.

I hope they do read this post, but I'm not quite sure now: yesterday I saw update 3.66.985 was out, but after ugrading it was still crashing :(
I hope they will investigate suspected PR #3180 and fix it soon..

It's nearly been one month notifications of new messages is broken because of this bug, and it'll most probably undermine trust into the app for users who just want a working chat app.

Has someone managed to download / revert to 3.64 version without problems ? I couldn't find the link to 3.64 and thus tried some older version but when I did that, decryption errors occurred.

**Comment by Kyoshiro-san** [comment]
Well, I found some 3.64 prod versions available between builds number 975 and 978.
Build version 978 crashes the same way but 975 does not, if it helps the devs to pinpoint the problem.

Here's the download link https://wire-app.wire.com/android/prod/wire-prod-release-3.64.975.apk

Since you'll have to uninstall current Wire app to install it, you have to backup your history first. If you do not, you'll lose all previous content. So, this might take a while but you can backup history to file, remove app and install version 3.64.975 from APK, connect and restore backup before anything (you cannot do it later).

So far no decryption issues with that version.

**Comment by Maxattax97** [comment]
This has been fixed in the production version I updated today (3.66.985). From the log it appears they did revert the aforementioned commit.

This can be closed now.

**Comment by Kyoshiro-san** [comment]
Glad to read that, so everything's working fine now ?
That's a bit odd they didn't bump the build number though, it's the same build number I tested.

**Comment by makingthematrix** [comment]
There was one bugfix in 3.66 which fixed most of the cases, but not all. Another one is coming with the next release, that is, in a week.
https://github.com/wireapp/wire-android/pull/3242
