### ISSUE TITLE
App demands a phone number

### ISSUE THREAD

**Issue by Bugsbane** [wireapp/wire-android#328]
The wire.com homepage says that one of the features of wire is being able to register without a phone number.

The Android app though seems to demand a phone number when registering. Can we make the app fit the marketing promise, please?

**Comment by someoneEsle** [comment]
You can register with email at app.wire.com and then sign in on your android phone using the email/pasword you provided. The only reason why the android client doesn't provide the option to register with email is developing priorities. I think it's already there in ios, and I'm pretty sure it's bound to come to android too because it's been requested many times.

**Comment by bjoernherbig** [comment]
Yes, phone number sign up on mobile is mandatory at the moment. e-mail sign up on desktop as described by @someoneEsle 
We are considering changes though. Closing this for now

**Comment by Bugsbane** [comment]
Then basically either the marketing should claim "No phone number required *for the web version*" or the mobile clients shouldn't demand one. At the very least add "(Coming soon to mobile)". Currently you are actually making a false promise. This is not helpful in building trust in an app whose primary benefit is being more trustworthy (the end user benefit of increased privacy, security etc).

**Comment by varac** [comment]
I agree with @Bugsbane. Please re-prioritize email-only registration for android, or change your documentation/website so ppl will know what to expect.
Having phone number as identifier is really bad from a privacy perspective, and wire should respect this.
Also, I wonder about a bad UX for android tablets without any mobile phone capacity ?
