### ISSUE TITLE
Idea for wire to make money

### ISSUE THREAD

**Issue by silvernode** [wireapp/wire-android#347]
Idea 1. Allow users to send money to contacts (probably bitcoin not really sure), take a cut.
Idea 2. Create a vanity store and charge developers for access, take a cut
Idea 3. A Create a vanity store and give free developer access and allow them to charge users for items, take a cut.

These are really the only things I can think of that won;t break the app.

There's another strange idea I had, basically a button that a user can click that allows them to donate any amount, that then triggers a button to be posted in the current chat window which the other person can click and donate. This can then be sent to another chosen user and thus spreads across the app naturally.

The only issue I can with this is that it might not be well received and seen as annoying. 

I really hope wire continues to grow and finds a way to stay alive. This might not be the correct place to put this but at least someone will see it. Thanks

**Comment by Cleanfer** [comment]
Idea 1. Would be nice if Wire could just stay focused on messaging.
Idea 2. Would be nice if Wire didn't become yet another bloated messaging app like FB Messenger, Line or Viber - making users have to skip offers of downloading that and that or swipe past ten buttons/screens before accessing what is easily accessible now, or accidentally enable this and that because 5000 gesture or buttons were added.
Idea 3. Would be nice if Wire could keep it's simple UI and not have to make room for tabs/more buttons just because of suggestions wanting to cram 50 apps/usage cases into one app.

The only thing I can think of is that people wanting to send money could use any of the other 10 billion apps offering that.

I really hope Wire continues to grow and stay alive and stay the clean, pure and slick messaging app it is.
Thanks.

**Comment by marcoconti83** [comment]
Hi @silvernode ,
Thanks for the suggestion and sorry for getting back to this ticket after so long! Quite a few things have changed, Wire has now a Pro version, targeted at businesses and organizations, with a paid subscription model. You can learn more about it on our [website](https://wire.com). Having the Pro versions allows us to maintain the free consumer version alongside, and we see no need to introduce any monetization to the consumer app.
