### ISSUE TITLE
Add Stickers

### ISSUE THREAD

**Issue by cwmke** [wireapp/wire-android#349]
It would be nice to add stickers to the app. Many successful apps like [WeChat](http://blog.wechat.com/tag/stickers/) and [Line](https://store.line.me/stickershop/home/general/en) have them. The XMPP client [Zom](https://zom.im/) has them as well. It could also be a way to monetize which could be included on the list in #347. Thanks either way.

**Comment by Cleanfer** [comment]
It would be nice if Wire could just stay focused on messaging.
It would be nice if Wire didn't become yet another bloated messaging app like FB Messenger, Line or Viber by - in the case of your suggestion: adding stickers and games - making users have to skip offers of downloading that and that or swipe past ten buttons/screens before accessing what is easily accessible now, or accidentally enable this and that because 5000 gesture or buttons were added.
It would be nice if wire could keep it's simple UI and not have to make room for tabs/more buttons just because of suggestions wanting to cram 50 apps/usage cases into one app.
So,t would be nice if people wanting to send money could use any of the other 10 billion apps offering that.

It would be nice if Wire could stay the clean, pure and slick messaging app it is.

Thanks either way.

**Comment by freijon** [comment]
I would like to have stickers too. I use stickers a lot to express emotions and I think it has become something essential for messaging.

**Comment by idamcevski** [comment]
It is a good thing to finally find a messaging app that is fast and reliable, minimal clean in design and all-round cross platform. Every add-on that improves the real usability of the messaging platform is more then welcome, encouraged even.

Stickers is just NOT one of them. As noted before, every other adolescent-oriented messenger app enables you to OMG and LOL your friends in vivid colours, so make good use of them.

On that note, please do not add stickers and keep Wire an app clean of gimmicks, or else the quest for one continues ...

**Comment by stormyqq** [comment]
me too. stickers are must to express the feelings better than words.

**Comment by instantchow** [comment]
Giphy integration pretty much closes this no? The only difference is that perhaps the images of the _Stickers_ would be internal not from an external server.

**Comment by cwmke** [comment]
I'm closing since it's simple to do this with apps now negating the need for chat apps to do so.

**Comment by WildYorkies** [comment]
@cwmke 

>it's simple to do this with apps now negating the need for chat apps to do so.

Can you explain what you mean by this?

There is a great design doc for Tox around this feature if you're interested https://wiki.tox.chat/developers/feature_ideas/stickers

@idamcevski 

>On that note, please do not add stickers and keep Wire an app clean of gimmicks

It's really too late for that. Wire already added the drawing feature (very gimmicky and less used than stickers). If you want a "no fun allowed" chat app, just stick to plain SMS. 

@Cleanfer 
>It would be nice if Wire didn't become yet another bloated messaging app

It already is, no? The UI has to be simplified with all of the message types already. Just simplify it and add one more option.
