### ISSUE TITLE
Message Notification

### ISSUE THREAD

**Issue by rider8581** [wireapp/wire-android#3571]
Good day.
Thank you for your contribution.
When there is a new message in the app, can I enable notification for them?

**Comment by makingthematrix** [comment]
Hi, @rider8581 .
The lack of notifications for some users is an ongoing problem in the Android app because of the amount of processing we do when a new message comes while the app is in the background or completely off.
You can follow this list of things you can do: https://support.wire.com/hc/en-us/articles/203624294-What-can-I-do-if-I-m-not-getting-any-notifications-on-Android-

If that doesn't help, then I can only ask you to wait> I have just started working on a new, much lighter implementation of this feature. There's a good chance it will improve the situation when it's done. Here's the link to the first PR: https://github.com/wireapp/wire-android/pull/3580
