### ISSUE TITLE
Play Store link is 404 / not found

### ISSUE THREAD

**Issue by supersandra** [wireapp/wire-android#3637]
**Describe the bug**
Following the link to download from the Play Store results in a 404 page.

**To Reproduce**

1. Go to https://wire.com/en/download/
2. Click Android
3. Click "Get from Play Store"
4. Get a 404 page on play.google.com

**Expected behavior**
The app's Play Store page loads and I can install the app from there.

**Additional context**
I was doing this on a desktop computer. I am in the US, in case the region matters.

**Comment by kroerig** [comment]
same here in Germany. Cannot find the app within Google Play Store.

**Comment by Dasm99** [comment]
Same in France.
Could we have an update about this issue ? 
Not been able to download the Android app is serious loss of fonctionnality...

**Comment by makingthematrix** [comment]
@supersandra , @kroerig , @Dasm99 :
During the Christmas - New Year break, Google decided to take Wire Android down from the App Store due to a technical problem with their review of our app. And since it was during the break, our reaction was delayed. It's all good now. Sorry for the inconvenience.

By the way, since December we are also on F-Droid:
https://www.f-droid.org/en/packages/com.wire/
