### ISSUE TITLE
messages lost

### ISSUE THREAD

**Issue by bruceleerabbit** [wireapp/wire-android#3687]
**Describe the bug**
When someone sends me messages they often get lost. The only reason I know that a message was sent is that on rare occasions I boot up a very old Debian desktop that runs the Wire electron app.  ***Some*** messages from one particular user never appear in the Wire Android app, only in the ancient desktop app.  The sender uses a desktop app only.

The temptation is to abandon the Android app, but I've actually abandoned the desktop app because the desktop app has abandoned Debian.  That is, the desktop app has fallen obsolete w.r.t current Debian libraries.  Bullseye is not supported.  The loss of the desktop as a workaround makes the bug herein even more crippling.

**To Reproduce**
I can’t say that it’s a reproducable problem.  Of the lost messages, *most* appear to be file attachments and all appear to be from one user in particular not other users.  These are fuzzy patterns.  I have nothing solid to go on.  Even the sender whose msgs are dropped can send msgs most of the time.

**Expected behavior**
I expect every single message that is transmitted to arrive on every single device of every single recipient.

**Screenshots**

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.38.xxx
- Last Wire version that did not exhibit the issue (if applicable): I didn't keep track of this - perhaps it was always a bug
- Android OS version used to run Wire: 5.1
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: n/a
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): wifi

**Additional context**
At first I suspected it was bug #1101, but in fact the one user whose messages are often lost has sent messages while I was offline and I received them.  And other users send msgs while i'm offline as well w/out issue.

**Comment by PhantomFighter** [comment]
Seconding. This has been going on a while, messages are often lost on the android side, while I can see them on the desktop side. I'm seeing this daily as I switch between desktop and android in a conversation.

**Comment by gopherit** [comment]
Thirding this. It's affected Wire for Android for at least one month, maybe 2-3 months.  Sometimes I send a message from Desktop to someone, and neither the recipient's Android phone nor my Android phone get my message.  The notification is delivered usually, just the message is not visible in the conversation once Wire is opened.

It's difficult to re-create this issue, but it happens in almost 100% of any back-and-forth conversations.

**Comment by gopherit** [comment]
Is the Android Development team running into staffing issues?  In my opinion, the issue of messages not appearing in the message conversation is high impact, high severity, as the message is gone forever, and it's annoying to have to constantly ask the sender to copy and paste the message again or take a screenshot.

This happens when both sending and receiving messages, and I've only seen it affect the Android app the past few months.  It happens daily and is hard to re-create.

I *think* if the Wire for Android app is actively open and on the screen, messages appear successfully.  But if it is in the background, often times only the message notification appears, but the message does not appear in the actual chat.

**Comment by gopherit** [comment]
I'm so apologize to nag.  I realize that the Android app is being rewritten separately, but this bug is a critical regression in my opinion.  Can this not be remediated at least until the newer Android app goes live?

There's not even any acknowledgement from the Wire developers in this repo, and this critical regression has been around for months now.

Thank you for your time and attention.

**Comment by gopherit** [comment]
My question is:  If you look at Wire's repositories on GitHub, why is literally every single repo getting work done within the past day **except** this repo?  Why deliberately ostracize a good portion of the userbase, **especially** over such a severe, critical bug?

It boggles the mind, and it's really appalling.  I used to be such a word-of-mouth champion for Wire, but this experience is really upsetting.  Every single repo is getting updated except this one, when there's an outstanding regression that was introduced in early 2022 in the Android app.  Why not simply squash this bug?

**Comment by vitorhugods** [comment]
Hello everyone.

This was the last major issue we tackled on this project, and it was fixed in https://github.com/wireapp/wire-android/pull/3715.

@gopherit was into something when they noticed this all other Wire repos are being updated **except** this.

I'm deeply sorry for the lack of communication in here, but this is not a secret anymore.  

We're currently building [a new Android client to replace this one](https://github.com/wireapp/wire-android-reloaded). It's more stable, faster and it provides a more intuitive experience in general.

For a visual representation on how drastic the changes in the new client are, you can take a look at the video [here](https://github.com/wireapp/wire-android-reloaded/pull/1080). Not only the UI, but the whole app is completely remade from scratch. The only thing we re-used is the E2EE protocol implementation.

It is not available publicly _yet_, but should be _soon_.
