### ISSUE TITLE
Messages do not show in the conversation

### ISSUE THREAD

**Issue by kroerig** [wireapp/wire-android#3707]
**Describe the bug**
Incoming messages appear as push-up, but do not show in the conversation.

**To Reproduce**
Write a message to a contact. Sometimes it happens.

**Expected behavior**
Messages to show up in the conversation again.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.80.23
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire: 11/ 12
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Samsung/ Sony
- Mobile network type (EDGE/LTE/Wi-Fi/Offline):

**Additional context**
I use Wire on three devices. One Android phone and two Windows Desktops.

**Comment by kroerig** [comment]
Maybe this is a related issue: https://github.com/wireapp/wire-android/issues/3687

**Comment by gopherit** [comment]
> Maybe this is a related issue: #3687

It is, in my opinion.

**Comment by vitorhugods** [comment]
Hello everyone.

This was the last major issue we tackled on this project, and it was fixed in https://github.com/wireapp/wire-android/pull/3715.

I'm deeply sorry for the lack of communication in here, but this is not a secret anymore.  

We're currently building [a new Android client to replace this one](https://github.com/wireapp/wire-android-reloaded). It's more stable, faster and it provides a more intuitive experience in general.

For a visual representation on how drastic the changes in the new client are, you can take a look at the video [here](https://github.com/wireapp/wire-android-reloaded/pull/1080). Not only the UI, but the whole app is completely remade from scratch. The only thing we re-used is the E2EE protocol implementation.

It is not available publicly _yet_, but should be _soon_.
