### ISSUE TITLE
Failed to build project on Android Studio Bumblebee 

### ISSUE THREAD

**Issue by kingfisherphuoc** [wireapp/wire-android#3708]
**Describe the bug**
I tried to build the source code the first time. When I synced the gradle file, I got this error message: 

```
cvc-complex-type.2.4.d: Invalid content was found starting with element 'base-extension'. No child element is expected at this point.
```

**To Reproduce**
1. Clone wire-android repo
2. Open the project with anddroid studio bumblebee
3. sync gradle file
4. See cvc error as above.

**Expected behavior**
The gradle sync should be success without any issue.

**Screenshots**
<img width="1740" alt="Screen Shot 2022-06-06 at 10 28 46" src="https://user-images.githubusercontent.com/962484/172089911-dfc5c40b-31bc-4b93-b0c8-199f50827c9f.png">

If it's not possible to fix, can you please tell me what's your android studio's version and your ndk's version? I assume that the project is not up-to-date with the latest android version. I tried to update `com.android.tools.build:gradle` to `7.0`, but it turned out that the `jp.leafytree.android-scala` plugin was not compatible with the latest Gradle build tool.

**Comment by vitorhugods** [comment]
Hello @kingfisherphuoc. Sorry for the late response.

This current project can be quite a pain to get right in order to build. Amongst other possible reasons, newer versions of Android Studio include the JDK 11, and JDK 8 in order to use it.

I'm not sure what are your needs by building this from source, but I highly encourage you to try our [new Android client](https://github.com/wireapp/wire-android-reloaded) instead.

Whilst it hasn't reached production yet, I think we're close to have a more reliable and fluid experience for Wire on Android by using this new client than the current one.

It's definitely easier to build!
