### ISSUE TITLE
Crash on start (F-Droid)

### ISSUE THREAD

**Issue by TheLastProject** [wireapp/wire-android#3721]
**Describe the bug**
Since the latest update on F-Droid Wire crashes for me on launch.

```
FATAL EXCEPTION: main
Process: com.wire, PID: 4104
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/JobIntentService;
	at com.evernote.android.job.JobManager.<init>(JobManager.java:148)
	at com.evernote.android.job.JobManager.create(JobManager.java:101)
	at com.waz.zclient.WireApplication.ensureInitialized(WireApplication.scala:441)
	at com.waz.zclient.WireApplication$$anonfun$ensureInitialized$4.apply(WireApplication.scala:1414)
	at scala.Option.fold(Option.scala:158)
	at com.waz.zclient.WireApplication.ensureInitialized(WireApplication.scala:413)
	at com.waz.zclient.WireApplication.onCreate(WireApplication.scala:404)
	at com.waz.zclient.ZApplication.onCreate(ZApplication.java:96)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ClassNotFoundException: android.support.v4.app.JobIntentService
	... 18 more
```

**To Reproduce**
1. Launch Wire
2. See error

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.81.36 (F-Droid)
- Android OS version used to run Wire: Android 11
- Is this a custom firmware or a stock one: LineageOS for microG
- Mobile phone model/manufacturer: Fairphone 3

**Comment by t1011** [comment]
+
LineageOS without GSF
Android 11

**Comment by froman753** [comment]
Similar issue, the app isn't crashing but it won't load at all. Only shows a blank black screen or black screen with the Wire logo in the center. Clearing the cache doesn't change anything. Unsure if deleting all app data may fix it, but I don't want to lose messages. 
Running GrapheneOS Android 12.

**Comment by Samuel-Huber** [comment]
Same issue with iodéOS (Android 12):
"Crashing at start"

**Comment by BehindTheBrain** [comment]
> Similar issue, the app isn't crashing but it won't load at all. Only shows a blank black screen or black screen with the Wire logo in the center. Clearing the cache doesn't change anything. Unsure if deleting all app data may fix it, but I don't want to lose messages. Running GrapheneOS Android 12.

Also running Graphene / 12. Clearing app data did not fix the issue. As of the latest update, Wire won't start.

**Comment by roberto-thy** [comment]
Same behavior, LineageOS Android 11.

**Comment by correctmeifimwrong33** [comment]
I, too, can't open Wire anymore on my phone, same problem it seems...

> Wire's constant malfunctions are annoying. I have to look for another messenger.

yeah, that's basically what I wrote support last week *before* this problem started. They said there would be a rewrite for Android by the end of the year, which suggested that, thus, they're not gonna solve anything in this version anymore. (I imagine blocking bugs like this would be picked up, but e.g. not phantom calls, reply displaying problems, etc.). The email ended with 'if there is anything else I can help with let me know'. Next day, this bug started and now I can't use Wire anymore at all, so I emailed back (this was Friday mid-afternoon, but they could have replied on Monday). Now that there is no easy reply to be had, such as "we'll ignore everything you said and instead announce a new release", they are a bit slower in responding :P. This is with a *paid* Wire account, by the way. Really makes me question what we're paying for, but the competition (Signal, Threema) are just missing features that Wire has had forever. (Or are (impressively) even less stable/reliable, like Element.) Recently we've been looking into things we can self host to avoid needing e2ee, broadening our options for replacing Wire with something more reliable.

Migrating would be annoying and take time though. Ideally, Wire would just get its act together before we decide on a replacement (will take months anyhow), fix the currently known bugs (even if you'd ignore Android until that rewrite is done, there's plenty of bugs on every other platform also), and then raise the price because honestly that would be worth it for me.

---

I also asked support if downgrading is safe, but no reply. Does anyone here know if one can downgrade to the previous f-droid release without then having to sign in again? If I lose the private key data, that would mean ~10 colleagues × 2-3 devices each would have to verify my new device fingerprint (which is yet another Wire-unique problem, Signal/Element do cross-signing devices just fine).

**Comment by froman753** [comment]
Looks like they just pushed out a hot fix with 3.81.37. Unfortunately the apk from the releases page here won't install over the previous f-droid version, so now just have to wait for the f_droid repository to be updated.

**Comment by b9AcE** [comment]
Wire is currently ["404 Page Not Found"](https://f-droid.org/en/packages/com.wire/) on F-Droid's webpage and missing from their apps-repository since at least two days.
Hope that is not intended and somehow considered as a solution to the still present crash-on-startup problem.

**Comment by TheLastProject** [comment]
Wire requested the F-Droid team to pull the broken release. Given that was the only release available at the time (other ones were pulled by the F-Droid team for proprietary code having slipped in that was detected by a recent F-Droid Scanner improvement), that caused 0 releases available and thus the 404 page.

The latest release has been successfully built (see https://monitor.f-droid.org) and should probably available in 1 to 3 days. Because that bumps the amount of available releases back to 1 the F-Droid page should reappear.

**Comment by froman753** [comment]
Update went live, notified by Neo Store. The app seems to work fine now, no issues with start up.

**Comment by b9AcE** [comment]
Yes, seconded: Wire is now available through F-Droid again and the new version (3.81.37) does not crash on startup for me, while the previous version did.
