### ISSUE TITLE
Developers don't bother acknowledging issues.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#3728]
It's been like that for years, issues get no reply for months if not years.

**Comment by vitorhugods** [comment]
Hello @Transisto.

As one of the developers of the application I must say we haven been lacking when maintaining this project for the past year or so indeed. It's been mainly in maintenance mode, focusing on critical issues.

But it's not all bad. It's not in vain.

We're creating a new Android application from scratch. The project is [here](https://github.com/wireapp/wire-android-reloaded/), and I can say a couple of facts:
- Our Android team has never been so big, so we're really invested in this.
- We are not far from releasing the new application.

While I can't say a date yet, we're polishing the basic functionality in order to replace the current application with a fresh and **stable** base that we can build on top of.

**Comment by J-Brk** [comment]
Hello @vitorhugods,

I'm glad to hear there is being worked on a new Android version and I look forward to the new release.

Non the less it's very concerning that Wire has been fine, ignoring its customers / users for such a long time on GitHub; even in the case where the issues that were so 'big' that it resulted in the application becoming pretty much unusable for some people.

I have always received great support by email, so it really surprises me that the opposite has been happening on here.

This is not something that should be happening; especially not for a professional product that is being sold.

**Comment by vitorhugods** [comment]
Thank you for the honest comments.

The support on GitHub is something the Android team can be ashamed of. I see that all of our other teams' repositories (iOS, Web, Desktop, Server, etc) are in a better shape than this one when it comes to maintenance and not leaving users hanging.

AFAIK, the reason to start the new project wasn't because the size of the issues alone, but it was aiming at replacing the current technology (Scala) for something more streamlined with the Android ecosystem nowadays (Kotlin).

Hiring Android developers with knowledge in Scala — or even willing to learn — is not something easy.

As I wasn't around when some decisions were made, I cannot explain everything in details, and I can judge even less.

But I can say that it's a personal desire of mine that we become more transparent and responsive on GitHub, and I will bring this concern to the team before the new project goes live.

In the coming weeks we should have a more concrete estimation on a release date and we can start making preparations to update this GitHub project accordingly.

**Comment by froman753** [comment]
Any estimation of release date for the new version dor Android?
