### ISSUE TITLE
Video compression / resize to high / adapt video file limit

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#435]
Hello,
please adapt the max video file size or change compression somehow because receiving resized HD material (see example) is really bad. U actually can't recognize anything...its worst if u get a 1080p origin material.
e.g.
- send a video file 720p, 112mb original size
- wire compresses to 25,8MB 560x320

Thank you
[videosize.txt](https://github.com/wireapp/wire-android/files/681487/videosize.txt)

**Comment by Gardosen** [comment]
after some test with the latest version of the client 3.46 i can say that the compression rate of the video is as intended.

i sadly can't tell from this report how the quality was in 2017, but i will close this ticket for now based on the fact that it is 3 years old.

If this issue is still a problem, feel free to create a new issue report based on the latest client.

Kind regards
Marco from the Android Team.
