### ISSUE TITLE
Better Ping/Call Behavior

### ISSUE THREAD

**Issue by 0xdade** [wireapp/wire-android#484]
I've noted this on twitter previously, but thought opening an actual ticket would be more useful to everyone.

We have a group chat of about 50 users that is regularly active. Unfortunately, on many phones the ping button is very close to the home button. Similarly, the call button, while generally far enough away from everything, is still easy to mistakenly hit.

My friend @aagallag built an [XPosed module](https://github.com/b0tchsec/Make-Wire-Great-Again) to disable outgoing calls and pings, but we've discussed better methods as well. The preferred solution, I think, is to provide a popup confirmation dialog when sending a ping or starting a call. 

This means that when accidentally hitting either button, it doesn't automatically bug the rest of the chat room, but doesn't remove the ability to send pings or calls entirely from large chats.

**Comment by tnguyen14** [comment]
I've having an issue with constantly hitting the Ping button by mistake as well.

On the iOS app, the ping button is part of the More menu (the one behind the 3 dots), which makes its use a bit more intentional. Can this be done on Android?

The idea of the confirmation dialog could work quite well for the call button. It might be a bit inconsistent for ping though.

Either way, having ping less easily accessible might be better.

**Comment by bjoernherbig** [comment]
Thanks for the feedback. We have some changes planned that will make it easier to choose the order. No timeline to share yet though.

**Comment by Gardosen** [comment]
i am closing this ticket now as it is over 3 years old and there was no response between now and then.

Kind regards
Marco from the Android Team
