### ISSUE TITLE
Cant build client app

### ISSUE THREAD

**Issue by Tyriod** [wireapp/wire-android#583]

**Comment by mykola-mokhnach** [comment]
Please provide more details on the issue (screenshots, error logs, etc.). Otherwise we will not be able to help.

**Comment by ronidee** [comment]
Although this issue is several months old already and Tyriod never responded, I wanna use this post to find some help while having the same problem (so I don't have to open another issue).

The following error occurs when I load the project: 
"Gradle sync failed: No such property: useAnt for class: org.gradle.api.tasks.scala.ScalaCompileOptions"

Thanks in advance for your help.

**Comment by marcoconti83** [comment]
Closing this one as duplicate of #985 (Thanks @archivebase for spotting it!)
