### ISSUE TITLE
Timed pictures doesn't work between Desktop/iOS and Android

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-android#602]
Timed pictures doesn't work between Desktop/iOS and Android.

- send a 5' picture from iOS 2.29 to Wire Android 2.27.314
- send a 5' texte from iOS 2.29 to Wire Android 2.27.314
- send a 5' picture from "Desktop" 2.11.2712 to Wire Android 2.27.314

Exepected: everything seen and sending disapear after 5'.

What append:

Wire Android 2.27.314 didn't seen any sending from iOS but only from desktop.
The iOS picture sending turned shadowed (meening time ending) but didn't disappear since the recipient didn't saw the sending. But the timed texte disappeared on iOS like it was saw (recipient said it was not).

Everything worked fine from "desktop".

PS: related to https://github.com/wireapp/wire-ios/issues/684

**Comment by someoneEsle** [comment]
I am struggling to understand what the issue is, but here are a couple of things that may be helpful:
- when sending a timed message from one of your devices, this *will not appear on the other devices you own*. It's by design
- when you send a timed message, the message will disappear on your device after the time is over, regardless of whether or not the other person has seen the message. If you send a message that disappears after 5 minutes, the following happens: 1. the message disappears on your device after 5 minutes; 2. once the other person opens wire and sees the message, a timer on their phone will start, counting down from 5 minutes: this timer is independent from the timer on your device, so that even though the message disappeared on your phone the other party may still be able to see it

**Comment by IpsmLorem** [comment]
Sorry. Let me try to be clearer.

>when you send a timed message, the message will disappear on your device after the time is over, regardless of whether or not the other person has seen the message. If you send a message that disappears after 5 minutes, the following happens: 1. the message disappears on your device after 5 minutes; 2. once the other person opens wire and sees the message, a timer on their phone will start, counting down from 5 minutes: this timer is independent from the timer on your device, so that even though the message disappeared on your phone the other party may still be able to see it. After 5 minutes, the message will disappear from their device.

I don't think so. My timed pictures deosn't work like that at all. They are hidden (text are scrambled) when the local time expire and disappear only when the recipient time expire.
The problem between iOS/Desktop and Android is the recipient doesn't see the sending and so their timer never expire and the scrambled or hidden local picture stays here forever (since you cannot even delete them).

**Comment by someoneEsle** [comment]
What do you mean by "the recipient doesn't see the sending"? That's the part I don't understand sorry :/

**Comment by IpsmLorem** [comment]
All my android recipients say that they cannot see any timed sending (picture or text).

**Comment by IpsmLorem** [comment]
Related to https://github.com/wireapp/wire-ios/issues/684

**Comment by IpsmLorem** [comment]
Bug still present and is very annoying. It ends up flooding my screen with unconfirmed timed messages.

**Comment by makingthematrix** [comment]
@IpsmLorem : The assets and the ephemeral messages functionality was rewritten since this ticket was opened. (And only now we finally catch up with all the opened tickets...)
I can't reproduce the bug. Can you tell me if it's still happening on your side?
