### ISSUE TITLE
Unable to type on android client. 

### ISSUE THREAD

**Issue by RahulReddy75** [wireapp/wire-android#609]
Description:
As a user, when i try to have a 1 to 1 private chat, i do not get the input box(to type the msg). 
It actually, works fine when i chat with the otto bot.

Device : Google nexus 5

**Comment by someoneEsle** [comment]
Does this happen with everyone, or only with one specific user? I remember this happened to me after doing the following:
- send a connection request to A
- cancel the connection request
- resend a connection request to A
- request gets accepted
- now I cannot send any message to A, because I do not have the text field
workaround: block A, unblock A, should now be able to text them.

**Comment by Rahul1992** [comment]
I am my case , i just sent the request and that is it, no notification that request was accepted, no text field.
The given workaround was successful. 
But i think this bug should be taken care of asap.

**Comment by makingthematrix** [comment]
This was fixed... probably a long time ago.
