### ISSUE TITLE
Switch to open source map service

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#734]
Wire is fantastic, finally, after a very long time of searching for a FOSS, encrypted chat service I've found one I can use and recommend. Thank you!

But I find it curious that a service where privacy and security is a key part, even to the point where you let us download the apk directly if we don't use Google Play Store (thank you for that!) still use Google Maps for your mapping feature. I don't want Google to know more about me/everyone than they already do, including places I'm interested in.

Please:

1. Let me use the map feature without Google Play Services
2. Stop sending those who click on a map link on desktop/web to Google Maps and switch to OpenStreetMaps or someone who uses data from OSM.
3. Let those who click on a map link in Android choose which map app to open.

Thanks again!

**Comment by nikolowry** [comment]
@forteller while we wait for this enhancement, I highly suggest using https://microg.org/download.html.  If you build AOSP from source you just have to apply the patches @microg supplies to enable signature spoofing. Otherwise if you use Xposed (which defeats the purpose of ensuring privacy) you can install the signature spoofing module from there.  

microG Pro Tip: Use the latest preview release, otherwise apps that use the newer version of Google Play Services will complain about your Play Services being out of date. I try to keep a strictly FOSS device but find myself occassionally downloading proprietary developed or distributed software for temporary usage with @yeriomin's https://github.com/yeriomin/YalpStore (Slack for work, Juno, an Uber-like service currently only in NYC, and now Wire)

Off-topic:
@wireapp needs to make it a priority to get this client to the point where it can be submitted to F-Droid. Any usage of a Google's proprietary services (distribution or jars) negates any claim of full-privacy.  You have no idea what their library is doing and it's more than probably it is fingerprinting devices and calling home.

I had to install the mobile client due to conversation history "feature" which has caused lost messages because I proactively clear my browser's cookies, cache and storage.

**Comment by forteller** [comment]
Thanks for all the info! I understand that changes like this will take time, but I'm thinking that just changing what website people who click on the link is sent to should be quite trivial?

Other than that, I'm sure you agree with me that microg is just an option for the nerdiest of the nerds and we need to make secure and privacy friendly systems that everyone can use, because even us nerds who care enough to use microg etc. are not safe if the wast majority of people are not safe. We all live in a society. :)

**Comment by nikolowry** [comment]
@forteller you are referring to the "share your location" view correct? It's not a webview,  the are using the Google Play Services maps class [https://github.com/wireapp/wire-android/blob/master/app/src/main/res/layout/fragment_location.xml], which makes replacing it exponentially more difficult and time consuming than just changing a url.

**Comment by forteller** [comment]
Yes, that's the feature I'm talking about. But if you receive one of those shared locations and you use Wire on desktop you are sent to maps.google.com in your browser. That's the link I'm talking about.

Also, just noticed: When clicking on it on Android, the Google Maps app opens up directly. I have it installed, unfortunately, but I'm not accepting the terms of service and won't use it. Instead we should be asked which mapps app we want to open the link in.

**Comment by nikolowry** [comment]
Ah gotcha, never actually generated the link and unfortunately don't have my phone near by.

That shouldn't be too difficult to do, just taking the lat/log and plugging it into a new URL for OSM

**Comment by forteller** [comment]
Yes, exactly. I've updated the issue to try to make my intention clearer, and also added a third point for those receiving a map link on Android.

**Comment by fungs** [comment]
The real issue here, IMO, is that instead of sending the location in a standardized neutral format that can be opened with whatever program you like, for instance OSMAnd on Android, it sends out links to the Google maps online service. The right way to do this would be to use the [GEO URI format](https://en.wikipedia.org/wiki/Geo_URI_scheme). Another additional convenience format would be a provider-independent web link.

**Comment by leonmvd** [comment]
I totally agree @fungs, would be so much better to use any app of choice to open (possibly even send) a location. There are more than enough alternatives to google nowadays both web and native (sdk's)

**Comment by makingthematrix** [comment]
Done. We use Open Street Maps now.
