### ISSUE TITLE
Feature request: comfort noise

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-android#754]
On Wire audio calls on an Android smartphone, I've sometimes heard the other person ask "Are you still there?", and I have done the same myself. When neither party is talking, if the codecs do silence suppression, i.e., transmit only a silence signal, it becomes impossible for the callers to distinguish between an active connection and a dropped connection.

In the telephone and cellphone world, the solution is for each end to generate comfort noise, i.e., a low level of background noise indicating to the person on the call that the connection is still active.

Wire should consider doing this.

**Comment by jspittka** [comment]
Thanks for this suggestion! We consciously decided against CNG, that's why Wire calls are perceived as very crisp and natural. CNG works great in the old telephone world but for wideband calls most users perceive CNG as annoying.

Our approach to signal users that a call is up or has gone down is by playing audio notifications. Otherwise reliability should be just so high that the question "are you still there" is not needed. Some of the audio notifications may have been broken during the roll out of the new calling protocol. We will review and fix potential defects soon.
