### ISSUE TITLE
Landscape mode / auto-rotation not supported

### ISSUE THREAD

**Issue by bjornwgnr** [wireapp/wire-android#78]
Please add support for landscape mode/auto-rotation.

>>LG G2 D802, Stock Lollipop 5.0.2, V30d-EUR-XX

**Comment by SIRSteiner** [comment]
I got the answer that there are no plans. But I think it is an important feature...

**Comment by teller** [comment]
Hi, @SIRSteiner is correct - there are no plans to implement landscape mode for phones. Main reason is the overhead it adds to design, dev and QA. As a small team we can't afford that if we want to keep the development speed.

**Comment by michl** [comment]
I understand the point but sadly that makes the app pretty much unusable with a physical keyboard. We are currently evaluating which messaging app to use and wire make a relay good impression except for this point. But it's kind of a show stopper here because of small screen phones with physical slide out keyboards.

**Comment by landry314** [comment]
well this is an absolute app killer for me. no landscape mode? really? i hate typing in portrait mode, it is horrible. i feel very uncomfortable using this app. too bad, because you have all the features... when you work out the bugs you could really be the best privacy messenger... but you need landscape mode. who agrees with me?

**Comment by xalmat** [comment]
Y'all need to reconsider this. This is a killer feature that you guys do not have, and it is hindering adoption.

**Comment by MeHannah** [comment]
Everyone should refuse to use a messenger, which does not offer landscape mode.

**Comment by landry314** [comment]
i mean, if you dont use landscape mode then you might like it anyway but i need landscape mode to type properly. i make too many errors in portrait mode.

signal is winning the privacy app battle for now.
