### ISSUE TITLE
Add a posibility to export a history log of contact (chat) to the .xml/other file on memory like in Signal

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-android#793]
Please, add a posibility to export a history log of contact (chat) to the .xml/other file on memory like it is made in Signal app. (Then a possibility to wipe the history, after exporting, if required).

*Added*: Import function is required too. This allows to export/import your history between devices, if required, like a backup feature. (Used in this manner in the Signal)

**Comment by ruppalsingh** [comment]
Related: #546

**Comment by 2114L3** [comment]
keeping the content encrypted to just the recipients would be of high preference
and messages with running timers to be excluded

**Comment by madranet** [comment]
Any official response on this?  It's been 9 months since the original request was made.

I'm in the same position myself. I need to get a new phone soon as my old one's faulty. But I've got months' worth of messages in Wire that I don't want to lose.  If not an official way of doing this at present, is there at least an unofficial way [eg. using ADB] whereby I can extract the messages DB and my encryption keys from my phone to keep them for future use, if an export/import feature is added?

**Comment by juliss95** [comment]
Unofficial way:
Titanium

Official way:
Backups are planned in Q1/Q2 of 2018 as far as i know

**Comment by metal450** [comment]
Wait, full backup/restore is implemented? My understanding was that backups still don't include media. Since when has that changed?

**Comment by madranet** [comment]
While the belated addition of a Backup/Restore facility is welcome, is there any reason it's so limited? As outlined in another issue: [1851](https://github.com/wireapp/wire-desktop/issues/1851) I've just lost a couple of years worth of Wire messages from my OSX laptop due to Wire storing its support files in a seemingly unrelated directory, which [not realising it was connected with Wire] I deleted.

I've got also got Wire installed on two Android devices and an OSX desktop. So, even though, I lost everything from the laptop, I was hopeful of getting it all back with the Restore function. However:

* Backups made from Wire on the Android devices can't be used to restore on the desktop version of the app. 

* Because I've not opened the copy of Wire.app on my desktop computer for a couple of months, when I did fire it up, all the messages are now rendered thus:

![2018-11-01_20-20-36](https://user-images.githubusercontent.com/669658/47877408-b9568480-de13-11e8-8110-474b4ec90772.png)

It seems that  messages over [28 days old can no longer be decrypted](https://github.com/wireapp/wire-desktop/issues/768#issuecomment-313922506) because the encryption keys will have expired.

So, in spite of having Wire installed on four different devices, it looks like I'm completely unable to restore the missing messages on one device, using any of the other three.  And, furthermore, it looks like, by not opening the Wire.app on another device within the previous 28 days, I've also lost the ability to decrypt all my previous messages on that device too.

Is this correct? 

Because, if so, I think people should be made aware just how little chance they have of restoring lost data, if they're not restoring it on the same device it was lost from and doing so within a relatively short timescale. Certainly not what I'd have expected from a much-anticipated Backup/Restore function.

**Comment by makingthematrix** [comment]
The current state of things:
1. New backup functionality is implemented which stores messages and other data in an encrypted file.
2. Media are not stored. You should be able to download them again from the backend if they weren't deleted yet. (that's after 4 weeks, afaik).
3. Bugs connected to invalid fingerprints and other backup restoration problems on Android are fixed. Although, this is a big feature so there's always a possiblity that's something is still wrong :( 
4. Cross-platform backup restoration is not possible. We discussed it and with new backup functionality it is technically possible, but we don't have time and people to work on it now. Sorry.

**Comment by metal450** [comment]
>     2. Media are not stored. You should be able to download them again from the backend if they weren't deleted yet. (that's after 4 weeks, afaik).

After waiting multiple years, I gave up on Wire & moved to Signal because of this. Backups that are missing all media are not backups.

**Comment by makingthematrix** [comment]
@hirusi : Back in 2020, the Wire Android team rewrote the backup functionality as zipped and encrypted JSON files, but we also decided that we don't have time and resources for anything more than that. We're just a few people with a lot of work on our hands and we have to be very careful about our priorities. In many cases the input from the open source community helps us or gives us arguments to do this or that feature or bugfix, but here there's nothing more we can do.

**Comment by hirusi** [comment]
That makes sense. I guess what I wanted to understand was whether the PR has any weight at all, or this feature is simply not on the roadmap and therefore will be not accepted as a contribution at all?

**Comment by makingthematrix** [comment]
@hirusi : This feature is not on our roadmap and we're unable to take it over and maintain it.
