### ISSUE TITLE
Support for Android 2.2+?

### ISSUE THREAD

**Issue by notnsane** [wireapp/wire-android#89]
I have an old Motorola Defy that is still kicking and rocking :stuck_out_tongue: I still use use quite a bit.

Do you guys plan to support these old versions? Or any reason why you can't support it anymore?

It's a shame because Whatsapp, Signal and Telegram all still give support for it :( But it's not a big deal.

**Comment by someoneEsle** [comment]
I remember asking the developers the same question a while ago -- I was asking about 4.1. They said they don't have the resources to focus on older versions whose user base is decreasing, and they'd rather focus on the most recent versions. Since you're asking about 2.2, I think the reasoning very much applies to you too :)

**Comment by notnsane** [comment]
Fair enough, thanks!
