### ISSUE TITLE
Interference with Skype

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-android#893]
## The problem

Wire behaves badly when skype is also running on the phone. Severe problems with receiving push notifications, can't establish calls (neither incoming, nor outgoing), photos not appearing, some messages lost, etc. When skype is closed, Wire behaves as it normally does (not perfect, but not this complete lack of operation).

## Environment

* Wire version that exhibits the issue: 2.33.335
* Android OS version used to run Wire: 6.0.1
* Is this a custom firmware or a stock one: Samsung stock
* Mobile phone model/manufacturer: Samsung J7
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/WiFi

## Details

It just stops working correctly after some time when skype is also running on the phone. The chat just shows that the contact called, no notifications for the call. Photos not appearing.

**Comment by david-wire** [comment]
Thanks for reporting this.
Could you send us some logs when this happens:
1. Go to Settings -> About
2. Tap "Wire swiss GmbH" 10 times
3. Reproduce your issue
4. Send the report from Settings -> Advanced -> Submit debug report
5. Go to Settings -> About
6. Tap "Wire swiss GmbH" 10 times again to disable detailed debug reports, because this slows down Wire
We can then follow up accordingly. Thanks!
