### ISSUE TITLE
How to increase group member limit?

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-android#929]
128 is a very low number.I want much higher! Can anyone instruct me to increase the limit?

**Comment by red-avtovo** [comment]
Hello @ProgrammerNinja! Thank you very much for your question!
Currently it is not possible to have more then 128 participants in a group chat. It is BackEnd limitation and you have nothing to do with that.
Maybe one day, this limit will be extended, but we don't have any plans on that right now

**Comment by grinapo** [comment]
@ProgrammerNinja as far as I see Wire keeps the limit artifically low so you can pay _5 euros per person per month_ to have a team account. They seem to politely avoid mention that. This is possibly the same reason that the "backend" is not open source, since then you could use large groups and other useful features.  That's what you get when there's a half-open codebase.
