### ISSUE TITLE
Why not supporting API level 14?

### ISSUE THREAD

**Issue by aurora-anon** [wireapp/wire-android#996]
#Build your software for API level 26, but also make it available for API level 14.
You don't have to bring all the features to lower API devices.
You could use lots of android.support libraries and backward compatiblity practices to make the app accessible for a wider range of devices.
You're losing a huge amount of users.
Look at the most popular softwares on Google Play and observe their minimum and target SDK versions.

**Comment by worldofpeace** [comment]
I agree with this. The more the devices you can support the better. Why are you not supporting API level 14?

**Comment by nidico** [comment]
What's the reason for the current API level >= 17 (Android 4.2) restriction? What is missing in API level 16 and lower?

**Comment by nidico** [comment]
I'm curious - why is this closed?

**Comment by aurora-potter** [comment]
Nothing special.
Just widening the app's API level support.
With a little effort, you can make it run on lower API levels.

**Comment by nidico** [comment]
I understand the intention of the issue, I just wondered why you closed that issue - e.g. if there is progress in that direction, or if you think this is not needed anymore... - I still think this lowering the minimum requirement would be helpful for Wire adoption.

**Comment by aurora-potter** [comment]
@nidico Now it's open, I hope you provide this compatibility.
You can use native libraries in many cases as an alternative to Java-based libraries.

**Comment by nidico** [comment]
Sorry, I'm not doing Android programming, so I can't do anything here. I was just asking why this issue has been closed.

**Comment by marcoconti83** [comment]
Hi everyone,

since last public version, Wire dropped support for Android 4.x. This is due lack of resources necessary to keep creating custom solutions for Android versions that are 5 years old, and inability to enforce certain security policies on those versions. I understand that this is a loss for Android 4.x users, but I'm afraid we won't be able to go back on this decision any time soon.

The lowest supported version is now officially 5.0.
